/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { CustomFieldInfo } from "./CustomFieldInfo";

export const CustomFieldsPatchResponse: core.serialization.ObjectSchema<
    serializers.CustomFieldsPatchResponse.Raw,
    Beehiiv.CustomFieldsPatchResponse
> = core.serialization.object({
    data: CustomFieldInfo.optional(),
});

export declare namespace CustomFieldsPatchResponse {
    interface Raw {
        data?: CustomFieldInfo.Raw | null;
    }
}
