/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { SubscriptionJwtToken } from "../../../types/SubscriptionJwtToken";

export const SubscriptionJwtTokenResponse: core.serialization.ObjectSchema<
    serializers.SubscriptionJwtTokenResponse.Raw,
    Beehiiv.SubscriptionJwtTokenResponse
> = core.serialization.object({
    data: SubscriptionJwtToken,
});

export declare namespace SubscriptionJwtTokenResponse {
    interface Raw {
        data: SubscriptionJwtToken.Raw;
    }
}
