/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { SubscriptionsPutResponseData } from "./SubscriptionsPutResponseData";

export const SubscriptionsPutResponse: core.serialization.ObjectSchema<
    serializers.SubscriptionsPutResponse.Raw,
    Beehiiv.SubscriptionsPutResponse
> = core.serialization.object({
    data: SubscriptionsPutResponseData,
});

export declare namespace SubscriptionsPutResponse {
    interface Raw {
        data: SubscriptionsPutResponseData.Raw;
    }
}
