/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const SubscriptionsListRequestOrderBy: core.serialization.Schema<
    serializers.SubscriptionsListRequestOrderBy.Raw,
    Beehiiv.SubscriptionsListRequestOrderBy
> = core.serialization.enum_(["created", "email"]);

export declare namespace SubscriptionsListRequestOrderBy {
    type Raw = "created" | "email";
}
