/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const SubscriptionDeleteResponse: core.serialization.ObjectSchema<
    serializers.SubscriptionDeleteResponse.Raw,
    Beehiiv.SubscriptionDeleteResponse
> = core.serialization.object({
    message: core.serialization.string().optional(),
});

export declare namespace SubscriptionDeleteResponse {
    interface Raw {
        message?: string | null;
    }
}
