/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const SubscriptionsPutRequestNewStatus: core.serialization.Schema<
    serializers.SubscriptionsPutRequestNewStatus.Raw,
    Beehiiv.SubscriptionsPutRequestNewStatus
> = core.serialization.enum_(["active", "inactive"]);

export declare namespace SubscriptionsPutRequestNewStatus {
    type Raw = "active" | "inactive";
}
