/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { Subscription } from "../../../types/Subscription";

export const SubscriptionsCreateResponse: core.serialization.ObjectSchema<
    serializers.SubscriptionsCreateResponse.Raw,
    Beehiiv.SubscriptionsCreateResponse
> = core.serialization.object({
    data: Subscription,
});

export declare namespace SubscriptionsCreateResponse {
    interface Raw {
        data: Subscription.Raw;
    }
}
