/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const SubscriptionsPatchResponseData: core.serialization.ObjectSchema<
    serializers.SubscriptionsPatchResponseData.Raw,
    Beehiiv.SubscriptionsPatchResponseData
> = core.serialization.object({
    subscriptionUpdateId: core.serialization.property("subscription_update_id", core.serialization.string().optional()),
});

export declare namespace SubscriptionsPatchResponseData {
    interface Raw {
        subscription_update_id?: string | null;
    }
}
