/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const SubscriptionsCreateRequestTier: core.serialization.Schema<
    serializers.SubscriptionsCreateRequestTier.Raw,
    Beehiiv.SubscriptionsCreateRequestTier
> = core.serialization.enum_(["free", "premium"]);

export declare namespace SubscriptionsCreateRequestTier {
    type Raw = "free" | "premium";
}
