/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../../index";

/**
 * @example
 *     {
 *         email: "bruce.wayne@wayneenterprise.com",
 *         reactivateExisting: false,
 *         sendWelcomeEmail: false,
 *         utmSource: "WayneEnterprise",
 *         utmMedium: "organic",
 *         utmCampaign: "fall_2022_promotion",
 *         referringSite: "www.wayneenterprise.com/blog",
 *         customFields: [{
 *                 name: "First Name",
 *                 value: "Bruce"
 *             }, {
 *                 name: "Last Name",
 *                 value: "Wayne"
 *             }],
 *         stripeCustomerId: "stripe_customer_id"
 *     }
 */
export interface SubscriptionsCreateRequest {
    /** The email address of the subscription. */
    email: string;
    /** Whether or not to reactivate the subscription if they have already unsubscribed. This option should be used only if the subscriber is knowingly resubscribing. */
    reactivateExisting?: boolean;
    sendWelcomeEmail?: boolean;
    /** The source of the subscription. */
    utmSource?: string;
    /** The medium of the subscription */
    utmMedium?: string;
    /** The acquisition campaign of the subscription */
    utmCampaign?: string;
    /** The website that the subscriber was referred from */
    referringSite?: string;
    /** This should be a subscribers referral_code. This gives referral credit for the new subscription. */
    referralCode?: string;
    /** The custom fields must already exist for the publication. Any new custom fields here will be discarded. */
    customFields?: Beehiiv.CustomFieldValue[];
    /** Override publication double-opt settings for this subscription. */
    doubleOptOverride?: Beehiiv.DoubleOptOverride;
    /** The tier for this subscription. */
    tier?: Beehiiv.SubscriptionsCreateRequestTier;
    /** The names of the premium tiers this subscription is associated with. Ignored if `premium_tier_ids` is given. */
    premiumTiers?: string[];
    /** The ids of the premium tiers this subscription is associated with. */
    premiumTierIds?: string[];
    /** The Stripe customer ID for this subscription. */
    stripeCustomerId?: string;
    /** Enroll the subscriber into automations after their subscription has been created. Requires the automations to have an active *Add by API* trigger. */
    automationIds?: string[];
}
