/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../../index";

/**
 * @example
 *     {}
 */
export interface SubscriptionsGetRequest {
    /**
     * Optional list of expandable objects.<br>`subscription_premium_tiers ` - Returns an array of tiers the subscription is associated with.<br>`referrals` - Returns an array of subscriptions with limited data - `id`, `email`, and `status`. These are the subscriptions that were referred by this subscription.<br>`stats` - Returns statistics about the subscription(s).<br>`custom_fields` - Returns an array of custom field values that have been set on the subscription. <br>`tags` - Returns an array of tags that have been set on the subscription.
     */
    expand?: Beehiiv.SubscriptionsGetRequestExpandItem | Beehiiv.SubscriptionsGetRequestExpandItem[];
}
