/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetPublicationsPublicationIdTiersTierIdRequest {
    /**
     * Optional list of expandable objects.<br>`stats` - Returns statistics about the tier(s).<br>`prices` - Returns prices for the tier(s).
     */
    expand?: string | string[];
}
