/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AutomationStatus = "running" | "finishing" | "inactive";

export const AutomationStatus = {
    Running: "running",
    Finishing: "finishing",
    Inactive: "inactive",
} as const;
