/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AutomationTriggerEvent =
    | "api"
    | "downgrade"
    | "email_submission"
    | "form_submission"
    | "manual"
    | "poll_submission"
    | "referral_action"
    | "segment_action"
    | "signup"
    | "unengaged"
    | "upgrade";

export const AutomationTriggerEvent = {
    Api: "api",
    Downgrade: "downgrade",
    EmailSubmission: "email_submission",
    FormSubmission: "form_submission",
    Manual: "manual",
    PollSubmission: "poll_submission",
    ReferralAction: "referral_action",
    SegmentAction: "segment_action",
    Signup: "signup",
    Unengaged: "unengaged",
    Upgrade: "upgrade",
} as const;
