/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../index";

/**
 * Details about specific URL's click stats from a post.
 */
export interface ClickStats {
    /** The URL the stats are for */
    url?: string;
    /** URL stats scoped only to email recipients. Not relevant for posts published only to web */
    email?: Beehiiv.PostClickStatsEmail;
    /** Stats scoped only to web views. Not relevant for posts published only to email */
    web?: Beehiiv.PostClickStatsWeb;
    totalClicks?: number;
    totalUniqueClicks?: number;
    /** The percentage of clicks on the URL compared to the total number of recipients and web views */
    totalClickThroughRate?: number;
}
