/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of value being stored in the custom field.
 */
export type CustomFieldType = "string" | "integer" | "boolean" | "date" | "datetime" | "list";

export const CustomFieldType = {
    String: "string",
    Integer: "integer",
    Boolean: "boolean",
    Date: "date",
    Datetime: "datetime",
    List: "list",
} as const;
