/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../index";

export interface CustomField {
    /** The name of the existing custom field */
    name?: string;
    /** The type of value being stored in the custom field. */
    kind?: Beehiiv.CustomFieldType;
    /** The value stored for the subscription */
    value?: Beehiiv.CustomFieldDataType;
}
