/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../index";

export interface EmailBlast {
    /** The prefixed email blast id */
    id: Beehiiv.EmailBlastId;
    /** The time the blast was created. Measured in seconds since the Unix epoch */
    created: number;
    /** The time the blast was last sent. Measured in seconds since the Unix epoch */
    lastSent: number;
    /** The status of the blast.<br>`inactive` - not been scheduled.<br>`active` - The blast is scheduled to send. */
    status: Beehiiv.EmailBlastStatus;
    /** The email subject line. */
    subjectLine: string;
    /** The email preview text */
    previewText: string;
    stats?: Beehiiv.EmailBlastStats;
    content?: Beehiiv.EmailBlastContent;
}
