/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EmailBlastStatsClicks {
    /** The URL the stats are for */
    url?: string;
    totalClicks?: number;
    totalUniqueClicks?: number;
    /** The percentage of clicks on the URL compared to the total number of recipients and web views */
    totalClickThroughRate?: number;
}
