/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../index";

/**
 * The reward object.
 */
export interface MilestoneReward {
    /** A unique prefixed id of the reward. */
    id: Beehiiv.RewardId;
    /** The name given to the reward at creation. */
    name: string;
    /** The description given to the name at creation. */
    description: string;
    /** A URL of an image to be displayed with the reward. */
    imageUrl: string;
    /** What type of reward this is.<br>`physical` - A product which must be sent to the subscriber.<br>`promo_code` - A code that is redeemable for goods or services. */
    type: Beehiiv.MilestoneRewardType;
}
