/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Stats scoped only to email recipients. Not relevant for posts published only to web
 */
export interface PostStatsEmail {
    /** Total number of email recipients */
    recipients?: number;
    /** Total number of emails delivered */
    delivered?: number;
    /** Total number of email opens */
    opens?: number;
    /** Total number of unique email opens */
    uniqueOpens?: number;
    /** The percentage of emails that have been opened */
    openRate?: number;
    /** Total number of email clicks */
    clicks?: number;
    /** Unique number of email clicks */
    uniqueClicks?: number;
    /** The percentage of emails that have been clicked */
    clickRate?: number;
    /** Total number of email unsubscribes */
    unsubscribes?: number;
    /** The number of subscribers that reported this post email as spam */
    spamReports?: number;
}
