/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * URL stats scoped only to email recipients. Not relevant for posts published only to web
 */
export interface PostClickStatsEmail {
    clicks?: number;
    uniqueClicks?: number;
    /** The percentage of email clicks on the URL compared to the total number of recipients */
    clickThroughRate?: number;
}
