/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Stats scoped only to web views. Not relevant for posts published only to email
 */
export interface PostClickStatsWeb {
    clicks?: number;
    uniqueClicks?: number;
    /** The percentage of clicks on the URL compared to the total number of web views */
    clickThroughRate?: number;
}
