/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../index";

/**
 * Optional list of stats for a post. Retrievable by including `expand: [stats]` in the post request body.
 */
export interface PostStats {
    /** Stats scoped only to email recipients. Not relevant for posts published only to web */
    email?: Beehiiv.PostStatsEmail;
    /** Stats scoped only to web views. Not relevant for posts published only to email */
    web?: Beehiiv.PostStatsWeb;
    /** An array of click statistics for each URL in the post */
    clicks?: Beehiiv.ClickStats[];
}
