/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The requested premium post HTML. This HTML does not have paywalls enforced.
 */
export interface PremiumPostContent {
    /** The website HTML rendered to a free reader */
    web?: string;
    /** The email HTML rendered to a premium reader */
    email?: string;
}
