/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The direction of the request. Defaults to `asc`.
 */
export type RequestDirection = "asc" | "desc";

export const RequestDirection = {
    Asc: "asc",
    Desc: "desc",
} as const;
