/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../index";

/**
 * The segment object. To expand results, see the results endpoint.
 */
export interface Segment {
    /** The prefixed ID of the segment. */
    id: Beehiiv.SegmentId;
    /** The name of the segment. */
    name: string;
    /** The type of segment.<br>`dynamic` - The segment is recalculated at set intervals.<br>`static` - The segment is calculated once at creation.<br>`manual` - The segment is not calculated at all. The results are created via CSV. */
    type: Beehiiv.SegmentType;
    /** The time the Segment was last calculated. Measured in seconds since the Unix epoch */
    lastCalculated?: number;
    /** The total number of subscriptions that belong in the segment from the last calculation. */
    totalResults: number;
    /** The status of the segment's most recent calculation.<br>`pending` - The segment has not been calculated yet.<br>`processing` - The calculation is in progress, and has not completed.<br>`completed` - The calculation was successful.<br>`failed` - Something went wrong during the calculation. */
    status: Beehiiv.SegmentStatus;
    /** Dynamic segments are marked inactive if they haven't been used in a specific period of time. Inactive segments will not automatically be recalculated. */
    active: boolean;
    stats?: Beehiiv.SegmentStats;
}
