/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the segment's most recent calculation.<br>`pending` - The segment has not been calculated yet.<br>`processing` - The calculation is in progress, and has not completed.<br>`completed` - The calculation was successful.<br>`failed` - Something went wrong during the calculation.
 */
export type SegmentStatus = "pending" | "processing" | "completed" | "failed";

export const SegmentStatus = {
    Pending: "pending",
    Processing: "processing",
    Completed: "completed",
    Failed: "failed",
} as const;
