/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../index";

/**
 * Optional list of tiers for a subscription. Retrievable by including `expand: [subscription_premium_tiers]` in the request body.
 */
export type SubscriptionTierList = Beehiiv.SubscriptionTierInfo[];
