/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The acquisition channel
 */
export type SubscriptionAcquisitionChannel =
    | ""
    | "website"
    | "import"
    | "embed"
    | "api"
    | "referral"
    | "recommendation"
    | "magic_link"
    | "boost"
    | "boost_send"
    | "boost_direct_link";

export const SubscriptionAcquisitionChannel = {
    Empty: "",
    Website: "website",
    Import: "import",
    Embed: "embed",
    Api: "api",
    Referral: "referral",
    Recommendation: "recommendation",
    MagicLink: "magic_link",
    Boost: "boost",
    BoostSend: "boost_send",
    BoostDirectLink: "boost_direct_link",
} as const;
