/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Optional list of tags for a subscription. Retrievable by including `expand: [tags]` in the request body.
 * Max limit of 100 unique tags per publication.
 */
export type SubscriptionTags = string[];
