/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The current tier of the subscription.
 */
export type SubscriptionExpandedTagsSubscriptionTier = "free" | "premium";

export const SubscriptionExpandedTagsSubscriptionTier = {
    Free: "free",
    Premium: "premium",
} as const;
