/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the subscription.<br>`validating` - The email address is being validated.<br>`invalid` - The email address is invalid.<br>`pending` - The email address is valid, but the subscription is pending double opt-in.<br>`active` - The email was valid and the subscription is active.<br>`inactive` - The subscription was made inactive, possibly due to an unsubscribe.<br>`needs_attention` - The subscription requires approval or denial.
 */
export type SubscriptionStatusWithTags =
    | "validating"
    | "invalid"
    | "pending"
    | "active"
    | "inactive"
    | "needs_attention";

export const SubscriptionStatusWithTags = {
    Validating: "validating",
    Invalid: "invalid",
    Pending: "pending",
    Active: "active",
    Inactive: "inactive",
    NeedsAttention: "needs_attention",
} as const;
