/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Optional list of stats for a subscription. Retrievable by including `expand: [stats]` in the request body.
 */
export interface SubscriptionStats {
    /** The total number of emails that have been sent to this subscriber */
    emailsReceived?: number;
    /** The percentage of emails that the subscriber has opened */
    openRate?: number;
    /** The percentage of emails that the subscriber has clicked a link in */
    clickThroughRate?: number;
}
