/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../index";

/**
 * Optional list of custom fields for a subscription. Retrievable by including `expand: [custom_field]` in the request body.
 */
export type SubscriptionCustomFieldList = Beehiiv.CustomField[];
