/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../../index";

/**
 * @example
 *     {
 *         url: "https://example.com/webhook",
 *         eventTypes: ["post.sent"]
 *     }
 */
export interface PostWebhooksRequest {
    /** The webhook URL to send events to. */
    url: string;
    /** The types of events the webhook will receive. */
    eventTypes: Beehiiv.WebhookEventType[];
    /** A description of the webhook. */
    description?: string;
}
