/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PublicationsListRequestOrderBy = "created" | "name";

export const PublicationsListRequestOrderBy = {
    Created: "created",
    Name: "name",
} as const;
