/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const ActiveFreeSubscriptionCount: core.serialization.Schema<
    serializers.ActiveFreeSubscriptionCount.Raw,
    Beehiiv.ActiveFreeSubscriptionCount
> = core.serialization.undiscriminatedUnion([core.serialization.number(), core.serialization.boolean()]);

export declare namespace ActiveFreeSubscriptionCount {
    type Raw = number | boolean;
}
