/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const ActiveSubscriptionCount: core.serialization.Schema<
    serializers.ActiveSubscriptionCount.Raw,
    Beehiiv.ActiveSubscriptionCount
> = core.serialization.undiscriminatedUnion([core.serialization.number(), core.serialization.boolean()]);

export declare namespace ActiveSubscriptionCount {
    type Raw = number | boolean;
}
