/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";
import { AutomationId } from "../resources/ids/types/AutomationId";
import { AutomationStatus } from "./AutomationStatus";
import { AutomationTriggerEvent } from "./AutomationTriggerEvent";

export const Automation: core.serialization.ObjectSchema<serializers.Automation.Raw, Beehiiv.Automation> =
    core.serialization.object({
        id: AutomationId,
        status: AutomationStatus,
        name: core.serialization.string(),
        triggerEvents: core.serialization.property("trigger_events", core.serialization.list(AutomationTriggerEvent)),
        description: core.serialization.string().optional(),
    });

export declare namespace Automation {
    interface Raw {
        id: AutomationId.Raw;
        status: AutomationStatus.Raw;
        name: string;
        trigger_events: AutomationTriggerEvent.Raw[];
        description?: string | null;
    }
}
