/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const AutomationJourneyStatus: core.serialization.Schema<
    serializers.AutomationJourneyStatus.Raw,
    Beehiiv.AutomationJourneyStatus
> = core.serialization.enum_(["initiated", "running", "in_progress", "completed", "failed"]);

export declare namespace AutomationJourneyStatus {
    type Raw = "initiated" | "running" | "in_progress" | "completed" | "failed";
}
