/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const AutomationTriggerEvent: core.serialization.Schema<
    serializers.AutomationTriggerEvent.Raw,
    Beehiiv.AutomationTriggerEvent
> = core.serialization.enum_([
    "api",
    "downgrade",
    "email_submission",
    "form_submission",
    "manual",
    "poll_submission",
    "referral_action",
    "segment_action",
    "signup",
    "unengaged",
    "upgrade",
]);

export declare namespace AutomationTriggerEvent {
    type Raw =
        | "api"
        | "downgrade"
        | "email_submission"
        | "form_submission"
        | "manual"
        | "poll_submission"
        | "referral_action"
        | "segment_action"
        | "signup"
        | "unengaged"
        | "upgrade";
}
