/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const AverageClickRate: core.serialization.Schema<serializers.AverageClickRate.Raw, Beehiiv.AverageClickRate> =
    core.serialization.undiscriminatedUnion([core.serialization.number(), core.serialization.boolean()]);

export declare namespace AverageClickRate {
    type Raw = number | boolean;
}
