/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const AverageOpenRate: core.serialization.Schema<serializers.AverageOpenRate.Raw, Beehiiv.AverageOpenRate> =
    core.serialization.undiscriminatedUnion([core.serialization.number(), core.serialization.boolean()]);

export declare namespace AverageOpenRate {
    type Raw = number | boolean;
}
