/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";
import { CustomFieldDataType } from "./CustomFieldDataType";

export const CustomFieldValue: core.serialization.ObjectSchema<
    serializers.CustomFieldValue.Raw,
    Beehiiv.CustomFieldValue
> = core.serialization.object({
    name: core.serialization.string().optional(),
    value: CustomFieldDataType.optional(),
});

export declare namespace CustomFieldValue {
    interface Raw {
        name?: string | null;
        value?: CustomFieldDataType.Raw | null;
    }
}
