/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const CustomFieldDataType: core.serialization.Schema<
    serializers.CustomFieldDataType.Raw,
    Beehiiv.CustomFieldDataType
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.number(),
    core.serialization.boolean(),
]);

export declare namespace CustomFieldDataType {
    type Raw = string | number | boolean;
}
