/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";
import { EmailBlastStatsEmail } from "./EmailBlastStatsEmail";
import { EmailBlastStatsClicks } from "./EmailBlastStatsClicks";

export const EmailBlastStats: core.serialization.ObjectSchema<
    serializers.EmailBlastStats.Raw,
    Beehiiv.EmailBlastStats
> = core.serialization.object({
    email: EmailBlastStatsEmail.optional(),
    clicks: core.serialization.list(EmailBlastStatsClicks).optional(),
});

export declare namespace EmailBlastStats {
    interface Raw {
        email?: EmailBlastStatsEmail.Raw | null;
        clicks?: EmailBlastStatsClicks.Raw[] | null;
    }
}
