/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";
import { EmailBlastContentEmail } from "./EmailBlastContentEmail";

export const EmailBlastContent: core.serialization.ObjectSchema<
    serializers.EmailBlastContent.Raw,
    Beehiiv.EmailBlastContent
> = core.serialization.object({
    email: EmailBlastContentEmail.optional(),
});

export declare namespace EmailBlastContent {
    interface Raw {
        email?: EmailBlastContentEmail.Raw | null;
    }
}
