/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";
import { EmailBlastId } from "../resources/ids/types/EmailBlastId";
import { EmailBlastStatus } from "./EmailBlastStatus";
import { EmailBlastStats } from "./EmailBlastStats";
import { EmailBlastContent } from "./EmailBlastContent";

export const EmailBlast: core.serialization.ObjectSchema<serializers.EmailBlast.Raw, Beehiiv.EmailBlast> =
    core.serialization.object({
        id: EmailBlastId,
        created: core.serialization.number(),
        lastSent: core.serialization.property("last_sent", core.serialization.number()),
        status: EmailBlastStatus,
        subjectLine: core.serialization.property("subject_line", core.serialization.string()),
        previewText: core.serialization.property("preview_text", core.serialization.string()),
        stats: EmailBlastStats.optional(),
        content: EmailBlastContent.optional(),
    });

export declare namespace EmailBlast {
    interface Raw {
        id: EmailBlastId.Raw;
        created: number;
        last_sent: number;
        status: EmailBlastStatus.Raw;
        subject_line: string;
        preview_text: string;
        stats?: EmailBlastStats.Raw | null;
        content?: EmailBlastContent.Raw | null;
    }
}
