/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const EmailBlastStatsClicks: core.serialization.ObjectSchema<
    serializers.EmailBlastStatsClicks.Raw,
    Beehiiv.EmailBlastStatsClicks
> = core.serialization.object({
    url: core.serialization.string().optional(),
    totalClicks: core.serialization.property("total_clicks", core.serialization.number().optional()),
    totalUniqueClicks: core.serialization.property("total_unique_clicks", core.serialization.number().optional()),
    totalClickThroughRate: core.serialization.property(
        "total_click_through_rate",
        core.serialization.number().optional()
    ),
});

export declare namespace EmailBlastStatsClicks {
    interface Raw {
        url?: string | null;
        total_clicks?: number | null;
        total_unique_clicks?: number | null;
        total_click_through_rate?: number | null;
    }
}
