/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";
import { ErrorDetail } from "./ErrorDetail";

export const Error_: core.serialization.ObjectSchema<serializers.Error_.Raw, Beehiiv.Error_> =
    core.serialization.object({
        status: core.serialization.number(),
        statusText: core.serialization.string(),
        errors: core.serialization.list(ErrorDetail),
    });

export declare namespace Error_ {
    interface Raw {
        status: number;
        statusText: string;
        errors: ErrorDetail.Raw[];
    }
}
