/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const ErrorDetail: core.serialization.ObjectSchema<serializers.ErrorDetail.Raw, Beehiiv.ErrorDetail> =
    core.serialization.object({
        message: core.serialization.string(),
        code: core.serialization.string(),
    });

export declare namespace ErrorDetail {
    interface Raw {
        message: string;
        code: string;
    }
}
