/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const PostClickStatsWeb: core.serialization.ObjectSchema<
    serializers.PostClickStatsWeb.Raw,
    Beehiiv.PostClickStatsWeb
> = core.serialization.object({
    clicks: core.serialization.number().optional(),
    uniqueClicks: core.serialization.property("unique_clicks", core.serialization.number().optional()),
    clickThroughRate: core.serialization.property("click_through_rate", core.serialization.number().optional()),
});

export declare namespace PostClickStatsWeb {
    interface Raw {
        clicks?: number | null;
        unique_clicks?: number | null;
        click_through_rate?: number | null;
    }
}
