/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";
import { PostStatsEmail } from "./PostStatsEmail";
import { PostStatsWeb } from "./PostStatsWeb";
import { ClickStats } from "./ClickStats";

export const PostStats: core.serialization.ObjectSchema<serializers.PostStats.Raw, Beehiiv.PostStats> =
    core.serialization.object({
        email: PostStatsEmail.optional(),
        web: PostStatsWeb.optional(),
        clicks: core.serialization.list(ClickStats).optional(),
    });

export declare namespace PostStats {
    interface Raw {
        email?: PostStatsEmail.Raw | null;
        web?: PostStatsWeb.Raw | null;
        clicks?: ClickStats.Raw[] | null;
    }
}
