/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const PostPlatform: core.serialization.Schema<serializers.PostPlatform.Raw, Beehiiv.PostPlatform> =
    core.serialization.enum_(["web", "email", "both"]);

export declare namespace PostPlatform {
    type Raw = "web" | "email" | "both";
}
