/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";
import { FreePostContent } from "./FreePostContent";
import { PremiumPostContent } from "./PremiumPostContent";

export const PostContent: core.serialization.ObjectSchema<serializers.PostContent.Raw, Beehiiv.PostContent> =
    core.serialization.object({
        free: FreePostContent.optional(),
        premium: PremiumPostContent.optional(),
    });

export declare namespace PostContent {
    interface Raw {
        free?: FreePostContent.Raw | null;
        premium?: PremiumPostContent.Raw | null;
    }
}
