/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const PremiumPostContent: core.serialization.ObjectSchema<
    serializers.PremiumPostContent.Raw,
    Beehiiv.PremiumPostContent
> = core.serialization.object({
    web: core.serialization.string().optional(),
    email: core.serialization.string().optional(),
});

export declare namespace PremiumPostContent {
    interface Raw {
        web?: string | null;
        email?: string | null;
    }
}
