/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const SegmentStats: core.serialization.ObjectSchema<serializers.SegmentStats.Raw, Beehiiv.SegmentStats> =
    core.serialization.object({
        openRate: core.serialization.property("open_rate", core.serialization.number()),
        totalSent: core.serialization.property("total_sent", core.serialization.number()),
        percentagePremiumSubscribers: core.serialization.property(
            "percentage_premium_subscribers",
            core.serialization.number()
        ),
        percentageSubscribersWithReferrals: core.serialization.property(
            "percentage_subscribers_with_referrals",
            core.serialization.number()
        ),
        uniqueEmailsClicked: core.serialization.property("unique_emails_clicked", core.serialization.number()),
        totalDelivered: core.serialization.property("total_delivered", core.serialization.number()),
        totalReferrals: core.serialization.property("total_referrals", core.serialization.number()),
        unsubscribedRate: core.serialization.property("unsubscribed_rate", core.serialization.number()),
        totalSubscribers: core.serialization.property("total_subscribers", core.serialization.number()),
        clickthroughRate: core.serialization.property("clickthrough_rate", core.serialization.number()),
        unsubscribedCount: core.serialization.property("unsubscribed_count", core.serialization.number()),
        uniqueEmailsOpened: core.serialization.property("unique_emails_opened", core.serialization.number()),
        premiumSubscribers: core.serialization.property("premium_subscribers", core.serialization.number()),
        averageReferralsPerSubscriber: core.serialization.property(
            "average_referrals_per_subscriber",
            core.serialization.number()
        ),
    });

export declare namespace SegmentStats {
    interface Raw {
        open_rate: number;
        total_sent: number;
        percentage_premium_subscribers: number;
        percentage_subscribers_with_referrals: number;
        unique_emails_clicked: number;
        total_delivered: number;
        total_referrals: number;
        unsubscribed_rate: number;
        total_subscribers: number;
        clickthrough_rate: number;
        unsubscribed_count: number;
        unique_emails_opened: number;
        premium_subscribers: number;
        average_referrals_per_subscriber: number;
    }
}
