/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const SubscriptionTags: core.serialization.Schema<serializers.SubscriptionTags.Raw, Beehiiv.SubscriptionTags> =
    core.serialization.list(core.serialization.string());

export declare namespace SubscriptionTags {
    type Raw = string[];
}
