/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";
import { CustomField } from "./CustomField";

export const SubscriptionCustomFieldList: core.serialization.Schema<
    serializers.SubscriptionCustomFieldList.Raw,
    Beehiiv.SubscriptionCustomFieldList
> = core.serialization.list(CustomField);

export declare namespace SubscriptionCustomFieldList {
    type Raw = CustomField.Raw[];
}
