/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const SubscriptionTierInfoStatus: core.serialization.Schema<
    serializers.SubscriptionTierInfoStatus.Raw,
    Beehiiv.SubscriptionTierInfoStatus
> = core.serialization.enum_(["active", "archived"]);

export declare namespace SubscriptionTierInfoStatus {
    type Raw = "active" | "archived";
}
