/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const SubscriptionStats: core.serialization.ObjectSchema<
    serializers.SubscriptionStats.Raw,
    Beehiiv.SubscriptionStats
> = core.serialization.object({
    emailsReceived: core.serialization.property("emails_received", core.serialization.number().optional()),
    openRate: core.serialization.property("open_rate", core.serialization.number().optional()),
    clickThroughRate: core.serialization.property("click_through_rate", core.serialization.number().optional()),
});

export declare namespace SubscriptionStats {
    interface Raw {
        emails_received?: number | null;
        open_rate?: number | null;
        click_through_rate?: number | null;
    }
}
