/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";
import { SubscriptionId } from "../resources/ids/types/SubscriptionId";
import { SubscriptionExpandedStatus } from "./SubscriptionExpandedStatus";
import { SubscriptionExpandedSubscriptionTier } from "./SubscriptionExpandedSubscriptionTier";
import { SubscriptionExpandedUtmChannel } from "./SubscriptionExpandedUtmChannel";
import { SubscriptionTierList } from "./SubscriptionTierList";
import { SubscriptionCustomFieldList } from "./SubscriptionCustomFieldList";
import { SubscriptionTags } from "./SubscriptionTags";
import { SubscriptionStats } from "./SubscriptionStats";
import { SubscriptionTierInfo } from "./SubscriptionTierInfo";
import { CustomField } from "./CustomField";

export const Subscription: core.serialization.ObjectSchema<serializers.Subscription.Raw, Beehiiv.Subscription> =
    core.serialization.object({
        id: SubscriptionId,
        email: core.serialization.string(),
        status: SubscriptionExpandedStatus,
        created: core.serialization.number(),
        subscriptionTier: core.serialization.property("subscription_tier", SubscriptionExpandedSubscriptionTier),
        subscriptionPremiumTierNames: core.serialization.property(
            "subscription_premium_tier_names",
            core.serialization.list(core.serialization.string())
        ),
        utmSource: core.serialization.property("utm_source", core.serialization.string()),
        utmMedium: core.serialization.property("utm_medium", core.serialization.string()),
        utmChannel: core.serialization.property("utm_channel", SubscriptionExpandedUtmChannel),
        utmCampaign: core.serialization.property("utm_campaign", core.serialization.string()),
        referringSite: core.serialization.property("referring_site", core.serialization.string()),
        referralCode: core.serialization.property("referral_code", core.serialization.string()),
        subscriptionPremiumTiers: core.serialization.property(
            "subscription_premium_tiers",
            SubscriptionTierList.optional()
        ),
        customFields: core.serialization.property("custom_fields", SubscriptionCustomFieldList.optional()),
        tags: SubscriptionTags.optional(),
        stats: SubscriptionStats.optional(),
    });

export declare namespace Subscription {
    interface Raw {
        id: SubscriptionId.Raw;
        email: string;
        status: SubscriptionExpandedStatus.Raw;
        created: number;
        subscription_tier: SubscriptionExpandedSubscriptionTier.Raw;
        subscription_premium_tier_names: string[];
        utm_source: string;
        utm_medium: string;
        utm_channel: SubscriptionExpandedUtmChannel.Raw;
        utm_campaign: string;
        referring_site: string;
        referral_code: string;
        subscription_premium_tiers?: SubscriptionTierList.Raw | null;
        custom_fields?: SubscriptionCustomFieldList.Raw | null;
        tags?: SubscriptionTags.Raw | null;
        stats?: SubscriptionStats.Raw | null;
    }
}
