/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";
import { SubscriptionTierInfo } from "./SubscriptionTierInfo";

export const SubscriptionTierList: core.serialization.Schema<
    serializers.SubscriptionTierList.Raw,
    Beehiiv.SubscriptionTierList
> = core.serialization.list(SubscriptionTierInfo);

export declare namespace SubscriptionTierList {
    type Raw = SubscriptionTierInfo.Raw[];
}
