/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";
import { TierId } from "../resources/ids/types/TierId";
import { SubscriptionTierInfoStatus } from "./SubscriptionTierInfoStatus";

export const SubscriptionTierInfo: core.serialization.ObjectSchema<
    serializers.SubscriptionTierInfo.Raw,
    Beehiiv.SubscriptionTierInfo
> = core.serialization.object({
    id: TierId,
    name: core.serialization.string(),
    status: SubscriptionTierInfoStatus,
});

export declare namespace SubscriptionTierInfo {
    interface Raw {
        id: TierId.Raw;
        name: string;
        status: SubscriptionTierInfoStatus.Raw;
    }
}
