/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const SubscriptionSubscriptionTier: core.serialization.Schema<
    serializers.SubscriptionSubscriptionTier.Raw,
    Beehiiv.SubscriptionSubscriptionTier
> = core.serialization.enum_(["free", "premium"]);

export declare namespace SubscriptionSubscriptionTier {
    type Raw = "free" | "premium";
}
