/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Beehiiv from "../../api/index";
import * as core from "../../core";

export const TotalEmailsSent: core.serialization.Schema<serializers.TotalEmailsSent.Raw, Beehiiv.TotalEmailsSent> =
    core.serialization.undiscriminatedUnion([core.serialization.number(), core.serialization.boolean()]);

export declare namespace TotalEmailsSent {
    type Raw = number | boolean;
}
