/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const SegmentOrderBy: core.serialization.Schema<serializers.SegmentOrderBy.Raw, Beehiiv.SegmentOrderBy> =
    core.serialization.enum_(["created", "last_calculated"]);

export declare namespace SegmentOrderBy {
    type Raw = "created" | "last_calculated";
}
