/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const SegmentRequestStatus: core.serialization.Schema<
    serializers.SegmentRequestStatus.Raw,
    Beehiiv.SegmentRequestStatus
> = core.serialization.enum_(["pending", "processing", "completed", "failed", "all"]);

export declare namespace SegmentRequestStatus {
    type Raw = "pending" | "processing" | "completed" | "failed" | "all";
}
