/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

/**
 * @example
 *     {
 *         data: {
 *             id: "aj_00000000-0000-0000-0000-000000000000",
 *             automationId: "aut_00000000-0000-0000-0000-000000000000",
 *             subscriptionId: "sub_00000000-0000-0000-0000-000000000000",
 *             email: "test@example.com",
 *             status: Beehiiv.AutomationJourneyStatus.Initiated,
 *             startedAt: 1714857600,
 *             completedAt: 1714861200
 *         }
 *     }
 */
export interface AutomationJourneysResponse {
    data: Beehiiv.AutomationJourney;
}
