/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

/**
 * @example
 *     {
 *         data: [{
 *                 id: "aj_00000000-0000-0000-0000-000000000000",
 *                 automationId: "aut_00000000-0000-0000-0000-000000000000",
 *                 subscriptionId: "sub_00000000-0000-0000-0000-000000000000",
 *                 email: "test@example.com",
 *                 status: Beehiiv.AutomationJourneyStatus.Initiated,
 *                 startedAt: 1714857600,
 *                 completedAt: 1714861200
 *             }, {
 *                 id: "aj_00000000-0000-0000-0000-000000000000",
 *                 automationId: "aut_00000000-0000-0000-0000-000000000000",
 *                 subscriptionId: "sub_00000000-0000-0000-0000-000000000000",
 *                 email: "test@example.com",
 *                 status: Beehiiv.AutomationJourneyStatus.Initiated,
 *                 startedAt: 1714857600,
 *                 completedAt: 1714861200
 *             }],
 *         limit: 10,
 *         page: 1,
 *         totalResults: 2,
 *         totalPages: 1
 *     }
 */
export interface AutomationJourneysIndexResponse {
    data: Beehiiv.AutomationJourney[];
    /** The limit placed on the results. If no limit was specified in the request, this defaults to 10. */
    limit: number;
    /** The page number the results are from. If no page was specified in the request, this defaults to page 1. */
    page: number;
    /** The total number of results from all pages. */
    totalResults: number;
    /** The total number of pages. */
    totalPages: number;
}
