/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const BulkSubscriptionUpdatesListResponseDataItemType: core.serialization.Schema<
    serializers.BulkSubscriptionUpdatesListResponseDataItemType.Raw,
    Beehiiv.BulkSubscriptionUpdatesListResponseDataItemType
> = core.serialization.enum_(["status", "bulk"]);

export declare namespace BulkSubscriptionUpdatesListResponseDataItemType {
    type Raw = "status" | "bulk";
}
