/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { BulkSubscriptionUpdatesListResponseDataItem } from "./BulkSubscriptionUpdatesListResponseDataItem";

export const BulkSubscriptionUpdatesListResponse: core.serialization.ObjectSchema<
    serializers.BulkSubscriptionUpdatesListResponse.Raw,
    Beehiiv.BulkSubscriptionUpdatesListResponse
> = core.serialization.object({
    data: core.serialization.list(BulkSubscriptionUpdatesListResponseDataItem).optional(),
});

export declare namespace BulkSubscriptionUpdatesListResponse {
    interface Raw {
        data?: BulkSubscriptionUpdatesListResponseDataItem.Raw[] | null;
    }
}
