/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const BulkSubscriptionUpdatesGetResponseDataStatus: core.serialization.Schema<
    serializers.BulkSubscriptionUpdatesGetResponseDataStatus.Raw,
    Beehiiv.BulkSubscriptionUpdatesGetResponseDataStatus
> = core.serialization.enum_(["pending", "processing", "complete", "failed"]);

export declare namespace BulkSubscriptionUpdatesGetResponseDataStatus {
    type Raw = "pending" | "processing" | "complete" | "failed";
}
