/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { BulkSubscriptionUpdatesGetResponseData } from "./BulkSubscriptionUpdatesGetResponseData";

export const BulkSubscriptionUpdatesGetResponse: core.serialization.ObjectSchema<
    serializers.BulkSubscriptionUpdatesGetResponse.Raw,
    Beehiiv.BulkSubscriptionUpdatesGetResponse
> = core.serialization.object({
    data: BulkSubscriptionUpdatesGetResponseData.optional(),
});

export declare namespace BulkSubscriptionUpdatesGetResponse {
    interface Raw {
        data?: BulkSubscriptionUpdatesGetResponseData.Raw | null;
    }
}
