/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { SubscriptionId } from "../../ids/types/SubscriptionId";
import { SubscriptionsPutRequestSubscriptionsItemTier } from "./SubscriptionsPutRequestSubscriptionsItemTier";
import { SubscriptionsPutRequestSubscriptionsItemCustomFieldsItem } from "./SubscriptionsPutRequestSubscriptionsItemCustomFieldsItem";

export const SubscriptionsPutRequestSubscriptionsItem: core.serialization.ObjectSchema<
    serializers.SubscriptionsPutRequestSubscriptionsItem.Raw,
    Beehiiv.SubscriptionsPutRequestSubscriptionsItem
> = core.serialization.object({
    subscriptionId: core.serialization.property("subscription_id", SubscriptionId),
    tier: SubscriptionsPutRequestSubscriptionsItemTier.optional(),
    stripeCustomerId: core.serialization.property("stripe_customer_id", core.serialization.string().optional()),
    unsubscribe: core.serialization.boolean().optional(),
    customFields: core.serialization.property(
        "custom_fields",
        core.serialization.list(SubscriptionsPutRequestSubscriptionsItemCustomFieldsItem).optional()
    ),
});

export declare namespace SubscriptionsPutRequestSubscriptionsItem {
    interface Raw {
        subscription_id: SubscriptionId.Raw;
        tier?: SubscriptionsPutRequestSubscriptionsItemTier.Raw | null;
        stripe_customer_id?: string | null;
        unsubscribe?: boolean | null;
        custom_fields?: SubscriptionsPutRequestSubscriptionsItemCustomFieldsItem.Raw[] | null;
    }
}
