/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { SubscriptionId } from "../../ids/types/SubscriptionId";
import { SubscriptionsPatchRequestSubscriptionsItemTier } from "./SubscriptionsPatchRequestSubscriptionsItemTier";
import { SubscriptionsPatchRequestSubscriptionsItemCustomFieldsItem } from "./SubscriptionsPatchRequestSubscriptionsItemCustomFieldsItem";

export const SubscriptionsPatchRequestSubscriptionsItem: core.serialization.ObjectSchema<
    serializers.SubscriptionsPatchRequestSubscriptionsItem.Raw,
    Beehiiv.SubscriptionsPatchRequestSubscriptionsItem
> = core.serialization.object({
    subscriptionId: core.serialization.property("subscription_id", SubscriptionId),
    tier: SubscriptionsPatchRequestSubscriptionsItemTier.optional(),
    stripeCustomerId: core.serialization.property("stripe_customer_id", core.serialization.string().optional()),
    unsubscribe: core.serialization.boolean().optional(),
    customFields: core.serialization.property(
        "custom_fields",
        core.serialization.list(SubscriptionsPatchRequestSubscriptionsItemCustomFieldsItem).optional()
    ),
});

export declare namespace SubscriptionsPatchRequestSubscriptionsItem {
    interface Raw {
        subscription_id: SubscriptionId.Raw;
        tier?: SubscriptionsPatchRequestSubscriptionsItemTier.Raw | null;
        stripe_customer_id?: string | null;
        unsubscribe?: boolean | null;
        custom_fields?: SubscriptionsPatchRequestSubscriptionsItemCustomFieldsItem.Raw[] | null;
    }
}
