/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const SubscriptionsPatchRequestSubscriptionsItemTier: core.serialization.Schema<
    serializers.SubscriptionsPatchRequestSubscriptionsItemTier.Raw,
    Beehiiv.SubscriptionsPatchRequestSubscriptionsItemTier
> = core.serialization.enum_(["free", "premium"]);

export declare namespace SubscriptionsPatchRequestSubscriptionsItemTier {
    type Raw = "free" | "premium";
}
