/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The tier for this subscription.
 */
export type SubscriptionsCreateRequestTier = "free" | "premium";

export const SubscriptionsCreateRequestTier = {
    Free: "free",
    Premium: "premium",
} as const;
