/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

/**
 * The response containing subscription data
 */
export interface SubscriptionResponse {
    data: Beehiiv.Subscription;
}
