/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Optional parameter to set the tier for this subscription.
 */
export type SubscriptionsPutRequestTier = "free" | "premium";

export const SubscriptionsPutRequestTier = {
    Free: "free",
    Premium: "premium",
} as const;
