/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SubscriptionsPutResponseData {
    /** The ID of the Subscription Update object responsible for handling the update job */
    subscriptionUpdateId?: string;
}
