/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

export interface SubscriptionsPutRequestCustomFieldsItem {
    /** The name of the existing custom field */
    name?: string;
    /** The value to stored for the subscription. Will be ignored if `delete: true` is included. */
    value?: Beehiiv.CustomFieldDataType;
    /** Optionally delete any value stored. If true, any passed in `value` attribute will be ignored. */
    delete?: boolean;
}
