/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SubscriptionsListRequestStatus = "validating" | "invalid" | "pending" | "active" | "inactive" | "all";

export const SubscriptionsListRequestStatus = {
    Validating: "validating",
    Invalid: "invalid",
    Pending: "pending",
    Active: "active",
    Inactive: "inactive",
    All: "all",
} as const;
