/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SubscriptionsListRequestOrderBy = "created" | "email";

export const SubscriptionsListRequestOrderBy = {
    Created: "created",
    Email: "email",
} as const;
