/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetPublicationsPublicationIdWebhooksWebhookIdTestsResponse {
    /** The test event. */
    data: Record<string, unknown>;
    /** The timestamp of the test event. */
    eventTimestamp: number;
    /** The type of webhook events that the endpoint is set up to receive. */
    eventType: string;
    /** The unique identifier for the test event. */
    uid: string;
}
