/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

export interface Webhook {
    /** The prefixed ID for the webhook. */
    id: Beehiiv.EndpointId;
    /** The webhook URL to send events to. */
    url: string;
    /** The date the webhook was created. Measured in seconds since the Unix epoch. */
    created: number;
    /** The date the webhook was last updated. Measured in seconds since the Unix epoch. */
    updated: number;
    /** The types of events the webhook will receive. */
    eventTypes: Beehiiv.WebhookEventType[];
    /** The user-defined description for the webhook. */
    description: string;
}
