/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

/**
 * A block in the post content.
 */
export type Block =
    | Beehiiv.Block.Paragraph
    | Beehiiv.Block.Image
    | Beehiiv.Block.Button
    | Beehiiv.Block.Heading
    | Beehiiv.Block.Rss
    | Beehiiv.Block.Advertisement
    | Beehiiv.Block.Columns
    | Beehiiv.Block.List
    | Beehiiv.Block.Table
    | Beehiiv.Block.Html
    | Beehiiv.Block.EmbedLink;

export declare namespace Block {
    interface Paragraph extends Beehiiv.ParagraphBlock {
        type: "paragraph";
    }

    interface Image extends Beehiiv.ImageBlock {
        type: "image";
    }

    interface Button extends Beehiiv.ButtonBlock {
        type: "button";
    }

    interface Heading extends Beehiiv.HeaderBlock {
        type: "heading";
    }

    interface Rss extends Beehiiv.RssBlock {
        type: "rss";
    }

    interface Advertisement extends Beehiiv.AdvertisementBlock {
        type: "advertisement";
    }

    interface Columns extends Beehiiv.ColumnsBlock {
        type: "columns";
    }

    interface List extends Beehiiv.ListBlock {
        type: "list";
    }

    interface Table extends Beehiiv.TableBlock {
        type: "table";
    }

    interface Html extends Beehiiv.HtmlBlock {
        type: "html";
    }

    interface EmbedLink extends Beehiiv.EmbedLinkBlock {
        type: "embed_link";
    }
}
