/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of block in the post.
 */
export type BlockType = "image" | "paragraph" | "button" | "heading" | "rss";

export const BlockType = {
    Image: "image",
    Paragraph: "paragraph",
    Button: "button",
    Heading: "heading",
    Rss: "rss",
} as const;
