/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

export interface ButtonBlock {
    /** The URL the button should use. */
    href: string;
    /** The text content of the button. */
    text: string;
    /** The target of the button (e.g., \_blank). */
    target?: string;
    /** The text alignment of the button. */
    alignment?: Beehiiv.TextAlignment;
    /** The size of the button (e.g., small, normal, large). */
    size?: Beehiiv.Sizes;
}
