/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

/**
 * A block in the post content that can be embedded within a column.
 */
export type EmbeddableBlocks =
    | Beehiiv.EmbeddableBlocks.Paragraph
    | Beehiiv.EmbeddableBlocks.Image
    | Beehiiv.EmbeddableBlocks.Button
    | Beehiiv.EmbeddableBlocks.Heading
    | Beehiiv.EmbeddableBlocks.Rss
    | Beehiiv.EmbeddableBlocks.Advertisement;

export declare namespace EmbeddableBlocks {
    interface Paragraph extends Beehiiv.ParagraphBlock {
        type: "paragraph";
    }

    interface Image extends Beehiiv.ImageBlock {
        type: "image";
    }

    interface Button extends Beehiiv.ButtonBlock {
        type: "button";
    }

    interface Heading extends Beehiiv.HeaderBlock {
        type: "heading";
    }

    interface Rss extends Beehiiv.RssBlock {
        type: "rss";
    }

    interface Advertisement extends Beehiiv.AdvertisementBlock {
        type: "advertisement";
    }
}
