/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The level of the header.
 */
export type HeadingLevel = "1" | "2" | "3" | "4" | "5" | "6";

export const HeadingLevel = {
    HeadingOne: "1",
    HeadingTwo: "2",
    HeadingThree: "3",
    HeadingFour: "4",
    HeadingFive: "5",
    HeadingSix: "6",
} as const;
