/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

export interface HeaderBlock {
    /** The level of the header (e.g., 1, 2, 3, etc.). */
    level: Beehiiv.HeadingLevel;
    /** The text alignment of the header (e.g., left, center, right). */
    textAlignment?: Beehiiv.TextAlignment;
    /** The text content of the header. */
    text: string;
    /** Whether the header should be an anchor header. */
    anchorHeader?: boolean;
    /** Whether the header should be included in the table of contents. */
    anchorIncludeInToc?: boolean;
}
