/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

export interface ParagraphBlock {
    /** The plaintext content of the paragraph. */
    plaintext?: string;
    /** The formatted content of the paragraph. */
    formattedText?: Beehiiv.ParagrahBlockTextSection[];
}
