/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ParagrahBlockTextSection {
    /** The text content of the paragraph. */
    text: string;
    /** The styling of the text (e.g., bold, italic). */
    styling?: string[];
}
