/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

export interface PostCreateBodyBase {
    /** The title of the post. */
    title: string;
    /** The subtitle of the post. */
    subtitle?: string;
    /** The ID of the template to use for the post. If not provided, the default template will be used. */
    postTemplateId?: Beehiiv.PostTemplateId;
    /** The time in which the post will be published. If not provided, the post will be published immediately. */
    scheduledAt?: Date;
    /** If true, custom link tracking will be enabled for this post. If not provided, the default value will be used. */
    customLinkTrackingEnabled?: boolean;
    /** The email capture type to use for this post. If not provided, the default value will be used. */
    emailCaptureTypeOverride?: Beehiiv.PostEmailCaptureTypeOverride;
    /** If you wish to display a date other than the scheduled_at date in the email, you can provide a date here. This will not affect the actual publish date of the post. */
    overrideScheduledAt?: Date;
    /** The social share type to use for this post. If not provided, the default value will be used. */
    socialShare?: Beehiiv.PostSocialShare;
    /** The URL of the thumbnail image to use for the post. If not provided, the default value will be used. */
    thumbnailImageUrl?: string;
    /** The recipients to use for this post. If not provided, the default value will be used. */
    recipients?: Beehiiv.PostRecipients;
    /** The email settings to use for this post. If not provided, the default value will be used. */
    emailSettings?: Beehiiv.PostEmailSettings;
    /** The web settings to use for this post. If not provided, the default value will be used. */
    webSettings?: Beehiiv.PostWebSettings;
    /** The metadata to use for this post. If not provided, the default value will be used. */
    seoSettings?: Beehiiv.PostMetadata;
    /** The content tags to use for this post. If not provided, the default value will be used. */
    contentTags?: string[];
    /** The headers to use for this post. If not provided, the default value will be used. */
    headers?: Record<string, string>;
    /** The custom fields to use for this post. If not provided, the default value will be used. */
    customFields?: Record<string, string>;
}
