/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PostMetadata {
    defaultDescription?: string;
    defaultTitle?: string;
    ogDescription?: string;
    ogTitle?: string;
    twitterDescription?: string;
    twitterTitle?: string;
}
