/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

/**
 * The request to create a post.
 */
export type PostCreateRequest = Beehiiv.CreatePostRequestWithBodyContent | Beehiiv.CreatePostRequestWithBlocks;
