/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostAudienceFilter = "free" | "premium" | "all";

export const PostAudienceFilter = {
    Free: "free",
    Premium: "premium",
    All: "all",
} as const;
