/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostSocialShare = "comments_and_likes_only" | "with_comments_and_likes" | "top" | "none";

export const PostSocialShare = {
    CommentsAndLikesOnly: "comments_and_likes_only",
    WithCommentsAndLikes: "with_comments_and_likes",
    Top: "top",
    None: "none",
} as const;
