/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostStatusFilter = "draft" | "confirmed" | "archived" | "all";

export const PostStatusFilter = {
    Draft: "draft",
    Confirmed: "confirmed",
    Archived: "archived",
    All: "all",
} as const;
