/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostPlatformFilter = "web" | "email" | "both" | "all";

export const PostPlatformFilter = {
    Web: "web",
    Email: "email",
    Both: "both",
    All: "all",
} as const;
