/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostEmailCaptureTypeOverride = "none" | "gated" | "popup";

export const PostEmailCaptureTypeOverride = {
    None: "none",
    Gated: "gated",
    Popup: "popup",
} as const;
