/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PostEmailSettings {
    fromAddress?: string;
    customLiveUrl?: string;
    displayTitleInEmail?: boolean;
    displayBylineInEmail?: boolean;
    displaySubtitleInEmail?: boolean;
    emailHeaderEngagementButtons?: string;
    emailHeaderSocialShare?: string;
    emailPreviewText?: string;
    emailSubjectLine?: string;
}
