/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostsListRequestHiddenFromFeed = "all" | "true" | "false";

export const PostsListRequestHiddenFromFeed = {
    All: "all",
    True: "true",
    False: "false",
} as const;
