/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

export interface PostRecipients {
    web: Beehiiv.PostWebRecipients;
    email: Beehiiv.PostEmailRecipients;
}
