/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

export interface PostWebSettings {
    displayThumbnailOnWeb?: boolean;
    hideFromFeed?: boolean;
    paywallBreakPriceId?: Beehiiv.PriceId;
    paywallId?: Beehiiv.PaywallId;
    slug?: string;
}
