/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PostOrderBy = "created" | "publish_date" | "displayed_date";

export const PostOrderBy = {
    Created: "created",
    PublishDate: "publish_date",
    DisplayedDate: "displayed_date",
} as const;
