/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

/**
 * A block in the post content.
 */
export interface RssBlock {
    /** The ID of the external RSS feed. */
    externalRssFeedId?: Beehiiv.ExternalRssFeedId;
    /** The URL of the RSS feed. */
    rssFeedUrl?: string;
    /** The layout of the articles from the feed. */
    articleLayout?: Beehiiv.RssBlockLayout;
    /** The number of articles to show from the feed. */
    articlesToShow?: number;
    /** Whether to show a call to action. */
    showCta?: boolean;
    /** The text of the call to action. Applicable if ctaStyle is button or link. */
    ctaText?: string;
    /** The style of the call to action. */
    ctaStyle?: Beehiiv.RssCtaStyle;
    /** The alignment of the call to action. */
    ctaAlignment?: Beehiiv.RssCtaAlignment;
    /** Whether or not to refresh the contents from the RSS feed before sending out the email. */
    refreshOnSend?: boolean;
    /** Whether to show the article title. */
    showArticleTitle?: boolean;
    /** Whether to show the article thumbnail. */
    showArticleThumbnail?: boolean;
    /** The position of the thumbnail. */
    thumbnailPosition?: Beehiiv.RssThumbnailPosition;
    /** Whether to show the author. */
    showAuthor?: boolean;
    /** Whether to show the date the article was published */
    showPublishedDate?: boolean;
    /** Whether to show the categories. */
    showCategories?: boolean;
    /** Whether to show the article description. */
    showDescription?: boolean;
    /** Whether to show the article content. */
    showContent?: boolean;
}
