/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The sizes of the button.
 */
export type Sizes = "small" | "normal" | "large";

export const Sizes = {
    Small: "small",
    Normal: "normal",
    Large: "large",
} as const;
