/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

export interface TableCellData {
    /** The text content of the cell. */
    text: string;
    /** The text alignment of the cell. */
    alignment?: Beehiiv.TextAlignment;
}
