/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The text alignment of the header.
 */
export type TextAlignment = "left" | "center" | "right";

export const TextAlignment = {
    Left: "left",
    Center: "center",
    Right: "right",
} as const;
