/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Beehiiv from "../../../../../api/index";
import * as core from "../../../../../core";
import { SubscriptionsPatchRequestSubscriptionsItemTier } from "../../../bulkSubscriptionUpdates/types/SubscriptionsPatchRequestSubscriptionsItemTier";
import { SubscriptionsPatchRequestSubscriptionsItemCustomFieldsItem } from "../../../bulkSubscriptionUpdates/types/SubscriptionsPatchRequestSubscriptionsItemCustomFieldsItem";

export const SubscriptionsPatchSingleRequest: core.serialization.Schema<
    serializers.SubscriptionsPatchSingleRequest.Raw,
    Beehiiv.SubscriptionsPatchSingleRequest
> = core.serialization.object({
    tier: SubscriptionsPatchRequestSubscriptionsItemTier.optional(),
    stripeCustomerId: core.serialization.property("stripe_customer_id", core.serialization.string().optional()),
    unsubscribe: core.serialization.boolean().optional(),
    customFields: core.serialization.property(
        "custom_fields",
        core.serialization.list(SubscriptionsPatchRequestSubscriptionsItemCustomFieldsItem).optional()
    ),
});

export declare namespace SubscriptionsPatchSingleRequest {
    interface Raw {
        tier?: SubscriptionsPatchRequestSubscriptionsItemTier.Raw | null;
        stripe_customer_id?: string | null;
        unsubscribe?: boolean | null;
        custom_fields?: SubscriptionsPatchRequestSubscriptionsItemCustomFieldsItem.Raw[] | null;
    }
}
