/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Beehiiv from "../../../../../api/index";
import * as core from "../../../../../core";
import { SubscriptionsPutRequestSubscriptionsItemTier } from "../../../bulkSubscriptionUpdates/types/SubscriptionsPutRequestSubscriptionsItemTier";
import { SubscriptionsPutRequestSubscriptionsItemCustomFieldsItem } from "../../../bulkSubscriptionUpdates/types/SubscriptionsPutRequestSubscriptionsItemCustomFieldsItem";

export const SubscriptionsUpdateRequest: core.serialization.Schema<
    serializers.SubscriptionsUpdateRequest.Raw,
    Beehiiv.SubscriptionsUpdateRequest
> = core.serialization.object({
    tier: SubscriptionsPutRequestSubscriptionsItemTier.optional(),
    stripeCustomerId: core.serialization.property("stripe_customer_id", core.serialization.string().optional()),
    unsubscribe: core.serialization.boolean().optional(),
    customFields: core.serialization.property(
        "custom_fields",
        core.serialization.list(SubscriptionsPutRequestSubscriptionsItemCustomFieldsItem).optional()
    ),
});

export declare namespace SubscriptionsUpdateRequest {
    interface Raw {
        tier?: SubscriptionsPutRequestSubscriptionsItemTier.Raw | null;
        stripe_customer_id?: string | null;
        unsubscribe?: boolean | null;
        custom_fields?: SubscriptionsPutRequestSubscriptionsItemCustomFieldsItem.Raw[] | null;
    }
}
