/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../../index";

/**
 * @example
 *     {}
 */
export interface SegmentsShowRequest {
    /**
     * Optionally expand the response to include additional data. <br> `stats` - Requests the most recently calculated statistics for a segment. <br> Segment stats are recalculated once daily around 7 a.m. UTC for dynamic segments, but can be manually recalculated at any time in the dashboard. Manual and static segments only calculate once upon upload or creation.
     */
    expand?: Beehiiv.SegmentsExpandItems[];
}
