/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { Automation } from "../../../types/Automation";

export const AutomationsListResponse: core.serialization.ObjectSchema<
    serializers.AutomationsListResponse.Raw,
    Beehiiv.AutomationsListResponse
> = core.serialization.object({
    data: core.serialization.list(Automation).optional(),
    limit: core.serialization.number().optional(),
    page: core.serialization.number().optional(),
    totalResults: core.serialization.property("total_results", core.serialization.number().optional()),
    totalPages: core.serialization.property("total_pages", core.serialization.number().optional()),
});

export declare namespace AutomationsListResponse {
    interface Raw {
        data?: Automation.Raw[] | null;
        limit?: number | null;
        page?: number | null;
        total_results?: number | null;
        total_pages?: number | null;
    }
}
