/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { Automation } from "../../../types/Automation";

export const AutomationsGetResponse: core.serialization.ObjectSchema<
    serializers.AutomationsGetResponse.Raw,
    Beehiiv.AutomationsGetResponse
> = core.serialization.object({
    data: Automation.optional(),
});

export declare namespace AutomationsGetResponse {
    interface Raw {
        data?: Automation.Raw | null;
    }
}
