/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

/**
 * Price belonging to a Tier
 */
export interface TierPrice {
    id?: Beehiiv.PriceId;
    currency?: Beehiiv.TierPriceCurrency;
    amountCents?: number;
    enabled?: boolean;
    interval?: Beehiiv.TierPriceInterval;
    denominator?: string;
    /** When using the external Stripe checkout, this text will be displayed on the button */
    cta?: string;
    features?: string[];
}
