/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TierPriceInterval = "month" | "year";

export const TierPriceInterval = {
    Month: "month",
    Year: "year",
} as const;
