/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TierPriceCurrency = "usd" | "aud" | "cad" | "eur" | "inr" | "brl";

export const TierPriceCurrency = {
    Usd: "usd",
    Aud: "aud",
    Cad: "cad",
    Eur: "eur",
    Inr: "inr",
    Brl: "brl",
} as const;
