/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

export interface TierPricesAttributesItem {
    currency: Beehiiv.TierPriceCurrency;
    amountCents: number;
    enabled?: boolean;
    interval: Beehiiv.TierPriceInterval;
    intervalDisplay?: string;
    cta?: string;
    features?: string[];
}
