/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

/**
 * @example
 *     {
 *         id: "price_00000000-0000-0000-0000-000000000000",
 *         currency: Beehiiv.TierPriceCurrency.Usd,
 *         amountCents: 1000,
 *         interval: Beehiiv.TierPriceInterval.Month,
 *         intervalDisplay: "Monthly",
 *         cta: "Subscribe Now",
 *         features: ["Exclusive content"]
 *     }
 */
export interface UpdateTierPriceRequest {
    /** ID of the existing price. */
    id: Beehiiv.PriceId;
    currency: Beehiiv.TierPriceCurrency;
    amountCents: number;
    interval: Beehiiv.TierPriceInterval;
    intervalDisplay?: string;
    cta?: string;
    features?: string[];
    /** Optionally delete the price when updating the tier. */
    delete?: boolean;
}
