/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const AdvertisementBlock: core.serialization.ObjectSchema<
    serializers.AdvertisementBlock.Raw,
    Beehiiv.AdvertisementBlock
> = core.serialization.object({
    opportunityId: core.serialization.property("opportunity_id", core.serialization.string()),
});

export declare namespace AdvertisementBlock {
    interface Raw {
        opportunity_id: string;
    }
}
