/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const BlockType: core.serialization.Schema<serializers.BlockType.Raw, Beehiiv.BlockType> =
    core.serialization.enum_(["image", "paragraph", "button", "heading", "rss"]);

export declare namespace BlockType {
    type Raw = "image" | "paragraph" | "button" | "heading" | "rss";
}
