/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { TextAlignment } from "./TextAlignment";
import { Sizes } from "./Sizes";

export const ButtonBlock: core.serialization.ObjectSchema<serializers.ButtonBlock.Raw, Beehiiv.ButtonBlock> =
    core.serialization.object({
        href: core.serialization.string(),
        text: core.serialization.string(),
        target: core.serialization.string().optional(),
        alignment: TextAlignment.optional(),
        size: Sizes.optional(),
    });

export declare namespace ButtonBlock {
    interface Raw {
        href: string;
        text: string;
        target?: string | null;
        alignment?: TextAlignment.Raw | null;
        size?: Sizes.Raw | null;
    }
}
