/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { ColumnBlock } from "./ColumnBlock";

export const ColumnsBlock: core.serialization.ObjectSchema<serializers.ColumnsBlock.Raw, Beehiiv.ColumnsBlock> =
    core.serialization.object({
        columns: core.serialization.list(ColumnBlock),
    });

export declare namespace ColumnsBlock {
    interface Raw {
        columns: ColumnBlock.Raw[];
    }
}
