/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { EmbeddableBlocks } from "./EmbeddableBlocks";

export const ColumnBlock: core.serialization.ObjectSchema<serializers.ColumnBlock.Raw, Beehiiv.ColumnBlock> =
    core.serialization.object({
        blocks: core.serialization.list(EmbeddableBlocks),
    });

export declare namespace ColumnBlock {
    interface Raw {
        blocks: EmbeddableBlocks.Raw[];
    }
}
