/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const EmbedLinkBlock: core.serialization.ObjectSchema<serializers.EmbedLinkBlock.Raw, Beehiiv.EmbedLinkBlock> =
    core.serialization.object({
        url: core.serialization.string(),
    });

export declare namespace EmbedLinkBlock {
    interface Raw {
        url: string;
    }
}
