/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { HeadingLevel } from "./HeadingLevel";
import { TextAlignment } from "./TextAlignment";

export const HeaderBlock: core.serialization.ObjectSchema<serializers.HeaderBlock.Raw, Beehiiv.HeaderBlock> =
    core.serialization.object({
        level: HeadingLevel,
        textAlignment: TextAlignment.optional(),
        text: core.serialization.string(),
        anchorHeader: core.serialization.boolean().optional(),
        anchorIncludeInToc: core.serialization.boolean().optional(),
    });

export declare namespace HeaderBlock {
    interface Raw {
        level: HeadingLevel.Raw;
        textAlignment?: TextAlignment.Raw | null;
        text: string;
        anchorHeader?: boolean | null;
        anchorIncludeInToc?: boolean | null;
    }
}
