/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { TextAlignment } from "./TextAlignment";

export const ImageBlock: core.serialization.ObjectSchema<serializers.ImageBlock.Raw, Beehiiv.ImageBlock> =
    core.serialization.object({
        imageUrl: core.serialization.string(),
        url: core.serialization.string().optional(),
        title: core.serialization.string().optional(),
        altText: core.serialization.property("alt_text", core.serialization.string().optional()),
        caption: core.serialization.string().optional(),
        imageAlignment: TextAlignment.optional(),
        captionAlignment: TextAlignment.optional(),
        width: core.serialization.number().optional(),
    });

export declare namespace ImageBlock {
    interface Raw {
        imageUrl: string;
        url?: string | null;
        title?: string | null;
        alt_text?: string | null;
        caption?: string | null;
        imageAlignment?: TextAlignment.Raw | null;
        captionAlignment?: TextAlignment.Raw | null;
        width?: number | null;
    }
}
