/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const ListType: core.serialization.Schema<serializers.ListType.Raw, Beehiiv.ListType> = core.serialization.enum_(
    ["ordered", "unordered"]
);

export declare namespace ListType {
    type Raw = "ordered" | "unordered";
}
