/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { ListType } from "./ListType";

export const ListBlock: core.serialization.ObjectSchema<serializers.ListBlock.Raw, Beehiiv.ListBlock> =
    core.serialization.object({
        items: core.serialization.list(core.serialization.string()),
        listType: ListType.optional(),
        startNumber: core.serialization.number().optional(),
    });

export declare namespace ListBlock {
    interface Raw {
        items: string[];
        listType?: ListType.Raw | null;
        startNumber?: number | null;
    }
}
