/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { ParagrahBlockTextSection } from "./ParagrahBlockTextSection";

export const ParagraphBlock: core.serialization.ObjectSchema<serializers.ParagraphBlock.Raw, Beehiiv.ParagraphBlock> =
    core.serialization.object({
        plaintext: core.serialization.string().optional(),
        formattedText: core.serialization.list(ParagrahBlockTextSection).optional(),
    });

export declare namespace ParagraphBlock {
    interface Raw {
        plaintext?: string | null;
        formattedText?: ParagrahBlockTextSection.Raw[] | null;
    }
}
