/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const PostAudienceFilter: core.serialization.Schema<
    serializers.PostAudienceFilter.Raw,
    Beehiiv.PostAudienceFilter
> = core.serialization.enum_(["free", "premium", "all"]);

export declare namespace PostAudienceFilter {
    type Raw = "free" | "premium" | "all";
}
