/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const PostSocialShare: core.serialization.Schema<serializers.PostSocialShare.Raw, Beehiiv.PostSocialShare> =
    core.serialization.enum_(["comments_and_likes_only", "with_comments_and_likes", "top", "none"]);

export declare namespace PostSocialShare {
    type Raw = "comments_and_likes_only" | "with_comments_and_likes" | "top" | "none";
}
