/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { CreatePostRequestWithBodyContent } from "./CreatePostRequestWithBodyContent";
import { CreatePostRequestWithBlocks } from "./CreatePostRequestWithBlocks";

export const PostCreateRequest: core.serialization.Schema<
    serializers.PostCreateRequest.Raw,
    Beehiiv.PostCreateRequest
> = core.serialization.undiscriminatedUnion([CreatePostRequestWithBodyContent, CreatePostRequestWithBlocks]);

export declare namespace PostCreateRequest {
    type Raw = CreatePostRequestWithBodyContent.Raw | CreatePostRequestWithBlocks.Raw;
}
