/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const PostStatusFilter: core.serialization.Schema<serializers.PostStatusFilter.Raw, Beehiiv.PostStatusFilter> =
    core.serialization.enum_(["draft", "confirmed", "archived", "all"]);

export declare namespace PostStatusFilter {
    type Raw = "draft" | "confirmed" | "archived" | "all";
}
