/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const PostsDeleteResponse: core.serialization.ObjectSchema<
    serializers.PostsDeleteResponse.Raw,
    Beehiiv.PostsDeleteResponse
> = core.serialization.object({});

export declare namespace PostsDeleteResponse {
    interface Raw {}
}
