/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const PostExpandField: core.serialization.Schema<serializers.PostExpandField.Raw, Beehiiv.PostExpandField> =
    core.serialization.enum_([
        "stats",
        "free_web_content",
        "free_email_content",
        "free_rss_content",
        "premium_web_content",
        "premium_email_content",
    ]);

export declare namespace PostExpandField {
    type Raw =
        | "stats"
        | "free_web_content"
        | "free_email_content"
        | "free_rss_content"
        | "premium_web_content"
        | "premium_email_content";
}
