/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const PostMetadata: core.serialization.ObjectSchema<serializers.PostMetadata.Raw, Beehiiv.PostMetadata> =
    core.serialization.object({
        defaultDescription: core.serialization.property("default_description", core.serialization.string().optional()),
        defaultTitle: core.serialization.property("default_title", core.serialization.string().optional()),
        ogDescription: core.serialization.property("og_description", core.serialization.string().optional()),
        ogTitle: core.serialization.property("og_title", core.serialization.string().optional()),
        twitterDescription: core.serialization.property("twitter_description", core.serialization.string().optional()),
        twitterTitle: core.serialization.property("twitter_title", core.serialization.string().optional()),
    });

export declare namespace PostMetadata {
    interface Raw {
        default_description?: string | null;
        default_title?: string | null;
        og_description?: string | null;
        og_title?: string | null;
        twitter_description?: string | null;
        twitter_title?: string | null;
    }
}
