/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const PostPlatformFilter: core.serialization.Schema<
    serializers.PostPlatformFilter.Raw,
    Beehiiv.PostPlatformFilter
> = core.serialization.enum_(["web", "email", "both", "all"]);

export declare namespace PostPlatformFilter {
    type Raw = "web" | "email" | "both" | "all";
}
