/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const PostEmailCaptureTypeOverride: core.serialization.Schema<
    serializers.PostEmailCaptureTypeOverride.Raw,
    Beehiiv.PostEmailCaptureTypeOverride
> = core.serialization.enum_(["none", "gated", "popup"]);

export declare namespace PostEmailCaptureTypeOverride {
    type Raw = "none" | "gated" | "popup";
}
