/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { SegmentId } from "../../ids/types/SegmentId";

export const PostEmailRecipients: core.serialization.ObjectSchema<
    serializers.PostEmailRecipients.Raw,
    Beehiiv.PostEmailRecipients
> = core.serialization.object({
    tierIds: core.serialization.property("tier_ids", core.serialization.list(core.serialization.string()).optional()),
    includeSegmentIds: core.serialization.property(
        "include_segment_ids",
        core.serialization.list(SegmentId).optional()
    ),
    excludeSegmentIds: core.serialization.property(
        "exclude_segment_ids",
        core.serialization.list(SegmentId).optional()
    ),
});

export declare namespace PostEmailRecipients {
    interface Raw {
        tier_ids?: string[] | null;
        include_segment_ids?: SegmentId.Raw[] | null;
        exclude_segment_ids?: SegmentId.Raw[] | null;
    }
}
