/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { PriceId } from "../../ids/types/PriceId";
import { PaywallId } from "../../ids/types/PaywallId";

export const PostWebSettings: core.serialization.ObjectSchema<
    serializers.PostWebSettings.Raw,
    Beehiiv.PostWebSettings
> = core.serialization.object({
    displayThumbnailOnWeb: core.serialization.property(
        "display_thumbnail_on_web",
        core.serialization.boolean().optional()
    ),
    hideFromFeed: core.serialization.property("hide_from_feed", core.serialization.boolean().optional()),
    paywallBreakPriceId: core.serialization.property("paywall_break_price_id", PriceId.optional()),
    paywallId: core.serialization.property("paywall_id", PaywallId.optional()),
    slug: core.serialization.string().optional(),
});

export declare namespace PostWebSettings {
    interface Raw {
        display_thumbnail_on_web?: boolean | null;
        hide_from_feed?: boolean | null;
        paywall_break_price_id?: PriceId.Raw | null;
        paywall_id?: PaywallId.Raw | null;
        slug?: string | null;
    }
}
