/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const RssBlockLayout: core.serialization.Schema<serializers.RssBlockLayout.Raw, Beehiiv.RssBlockLayout> =
    core.serialization.enum_(["1-col", "2-col", "3-col", "4-col"]);

export declare namespace RssBlockLayout {
    type Raw = "1-col" | "2-col" | "3-col" | "4-col";
}
