/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { ExternalRssFeedId } from "../../ids/types/ExternalRssFeedId";
import { RssBlockLayout } from "./RssBlockLayout";
import { RssCtaStyle } from "./RssCtaStyle";
import { RssCtaAlignment } from "./RssCtaAlignment";
import { RssThumbnailPosition } from "./RssThumbnailPosition";

export const RssBlock: core.serialization.ObjectSchema<serializers.RssBlock.Raw, Beehiiv.RssBlock> =
    core.serialization.object({
        externalRssFeedId: ExternalRssFeedId.optional(),
        rssFeedUrl: core.serialization.string().optional(),
        articleLayout: RssBlockLayout.optional(),
        articlesToShow: core.serialization.number().optional(),
        showCta: core.serialization.boolean().optional(),
        ctaText: core.serialization.string().optional(),
        ctaStyle: RssCtaStyle.optional(),
        ctaAlignment: RssCtaAlignment.optional(),
        refreshOnSend: core.serialization.boolean().optional(),
        showArticleTitle: core.serialization.boolean().optional(),
        showArticleThumbnail: core.serialization.boolean().optional(),
        thumbnailPosition: RssThumbnailPosition.optional(),
        showAuthor: core.serialization.boolean().optional(),
        showPublishedDate: core.serialization.boolean().optional(),
        showCategories: core.serialization.boolean().optional(),
        showDescription: core.serialization.boolean().optional(),
        showContent: core.serialization.boolean().optional(),
    });

export declare namespace RssBlock {
    interface Raw {
        externalRssFeedId?: ExternalRssFeedId.Raw | null;
        rssFeedUrl?: string | null;
        articleLayout?: RssBlockLayout.Raw | null;
        articlesToShow?: number | null;
        showCta?: boolean | null;
        ctaText?: string | null;
        ctaStyle?: RssCtaStyle.Raw | null;
        ctaAlignment?: RssCtaAlignment.Raw | null;
        refreshOnSend?: boolean | null;
        showArticleTitle?: boolean | null;
        showArticleThumbnail?: boolean | null;
        thumbnailPosition?: RssThumbnailPosition.Raw | null;
        showAuthor?: boolean | null;
        showPublishedDate?: boolean | null;
        showCategories?: boolean | null;
        showDescription?: boolean | null;
        showContent?: boolean | null;
    }
}
