/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const RssCtaAlignment: core.serialization.Schema<serializers.RssCtaAlignment.Raw, Beehiiv.RssCtaAlignment> =
    core.serialization.enum_(["Left", "Center", "Right"]);

export declare namespace RssCtaAlignment {
    type Raw = "Left" | "Center" | "Right";
}
