/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const RssThumbnailPosition: core.serialization.Schema<
    serializers.RssThumbnailPosition.Raw,
    Beehiiv.RssThumbnailPosition
> = core.serialization.enum_([
    "Above Title",
    "Below Title",
    "Left of content",
    "Right of content",
    "Alternating Horizontally",
]);

export declare namespace RssThumbnailPosition {
    type Raw = "Above Title" | "Below Title" | "Left of content" | "Right of content" | "Alternating Horizontally";
}
