/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const Sizes: core.serialization.Schema<serializers.Sizes.Raw, Beehiiv.Sizes> = core.serialization.enum_([
    "small",
    "normal",
    "large",
]);

export declare namespace Sizes {
    type Raw = "small" | "normal" | "large";
}
