/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { TextAlignment } from "./TextAlignment";

export const TableCellData: core.serialization.ObjectSchema<serializers.TableCellData.Raw, Beehiiv.TableCellData> =
    core.serialization.object({
        text: core.serialization.string(),
        alignment: TextAlignment.optional(),
    });

export declare namespace TableCellData {
    interface Raw {
        text: string;
        alignment?: TextAlignment.Raw | null;
    }
}
