/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { TableCellData } from "./TableCellData";

export const TableBlock: core.serialization.ObjectSchema<serializers.TableBlock.Raw, Beehiiv.TableBlock> =
    core.serialization.object({
        rows: core.serialization.list(core.serialization.list(TableCellData)),
        headerRow: core.serialization.boolean().optional(),
        headerColumn: core.serialization.boolean().optional(),
    });

export declare namespace TableBlock {
    interface Raw {
        rows: TableCellData.Raw[][];
        headerRow?: boolean | null;
        headerColumn?: boolean | null;
    }
}
