/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const TextAlignment: core.serialization.Schema<serializers.TextAlignment.Raw, Beehiiv.TextAlignment> =
    core.serialization.enum_(["left", "center", "right"]);

export declare namespace TextAlignment {
    type Raw = "left" | "center" | "right";
}
