/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { Webhook } from "./Webhook";

export const WebhookResponse: core.serialization.ObjectSchema<
    serializers.WebhookResponse.Raw,
    Beehiiv.WebhookResponse
> = core.serialization.object({
    data: Webhook,
});

export declare namespace WebhookResponse {
    interface Raw {
        data: Webhook.Raw;
    }
}
