/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Beehiiv from "../../../../../api/index";
import * as core from "../../../../../core";
import { CustomFieldType } from "../../../../types/CustomFieldType";

export const CustomFieldsCreateRequest: core.serialization.Schema<
    serializers.CustomFieldsCreateRequest.Raw,
    Beehiiv.CustomFieldsCreateRequest
> = core.serialization.object({
    kind: CustomFieldType,
    display: core.serialization.string(),
});

export declare namespace CustomFieldsCreateRequest {
    interface Raw {
        kind: CustomFieldType.Raw;
        display: string;
    }
}
