/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Beehiiv from "../../../../../api/index";
import * as core from "../../../../../core";

export const CustomFieldsPutRequest: core.serialization.Schema<
    serializers.CustomFieldsPutRequest.Raw,
    Beehiiv.CustomFieldsPutRequest
> = core.serialization.object({
    display: core.serialization.string().optional(),
});

export declare namespace CustomFieldsPutRequest {
    interface Raw {
        display?: string | null;
    }
}
