/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

/**
 * @example
 *     {
 *         data: {
 *             id: "00000000-0000-0000-0000-000000000000",
 *             kind: Beehiiv.CustomFieldType.String,
 *             display: "Display",
 *             created: 1672531200
 *         }
 *     }
 */
export interface CustomFieldResponse {
    data?: Beehiiv.CustomFieldInfo;
}
