/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

/**
 * @example
 *     {
 *         data: [{
 *                 id: "00000000-0000-0000-0000-000000000000",
 *                 kind: Beehiiv.CustomFieldType.String,
 *                 display: "Display",
 *                 created: 1672531200
 *             }, {
 *                 id: "00000000-0000-0000-0000-000000000000",
 *                 kind: Beehiiv.CustomFieldType.String,
 *                 display: "Display",
 *                 created: 1672531200
 *             }],
 *         limit: 10,
 *         page: 1,
 *         totalResults: 20,
 *         totalPages: 2
 *     }
 */
export interface CustomFieldIndexResponse {
    data?: Beehiiv.CustomFieldInfo[];
    /** The limit placed on the results. If no limit was specified in the request, this defaults to 10. */
    limit?: number;
    /** The page number the results are from. If no page was specified in the request, this defaults to page 1. */
    page?: number;
    /** The total number of results from all pages. */
    totalResults?: number;
    /** The total number of pages. */
    totalPages?: number;
}
