/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const PublicationsListRequestOrderBy: core.serialization.Schema<
    serializers.PublicationsListRequestOrderBy.Raw,
    Beehiiv.PublicationsListRequestOrderBy
> = core.serialization.enum_(["created", "name"]);

export declare namespace PublicationsListRequestOrderBy {
    type Raw = "created" | "name";
}
