/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../../index";

/**
 * @example
 *     {
 *         title: "The Kitchen Sink Post (refactored version)",
 *         subtitle: "Contains lots of examples of each block type and the various settings you could use",
 *         blocks: [{
 *                 type: "heading",
 *                 level: "2",
 *                 textAlignment: "center",
 *                 text: "This is my block!!!",
 *                 anchorHeader: false,
 *                 anchorIncludeInToc: false
 *             }, {
 *                 type: "list",
 *                 listType: "ordered",
 *                 items: ["a", "b", "c"]
 *             }, {
 *                 type: "list",
 *                 listType: "ordered",
 *                 items: ["d", "e", "f"],
 *                 startNumber: 4
 *             }, {
 *                 type: "list",
 *                 listType: "unordered",
 *                 items: ["g", "h", "i"],
 *                 startNumber: 4
 *             }, {
 *                 type: "table",
 *                 headerRow: true,
 *                 headerColumn: true,
 *                 rows: [[{
 *                             text: "A"
 *                         }, {
 *                             text: "B",
 *                             alignment: "center"
 *                         }, {
 *                             text: "C",
 *                             alignment: "right"
 *                         }], [{
 *                             text: "D",
 *                             alignment: "right"
 *                         }, {
 *                             text: "E",
 *                             alignment: "center"
 *                         }, {
 *                             text: "F",
 *                             alignment: "left"
 *                         }]]
 *             }, {
 *                 type: "table",
 *                 rows: [[{
 *                             text: "A"
 *                         }, {
 *                             text: "B"
 *                         }, {
 *                             text: "C"
 *                         }], [{
 *                             text: "D"
 *                         }, {
 *                             text: "E"
 *                         }, {
 *                             text: "F"
 *                         }]]
 *             }, {
 *                 type: "table",
 *                 headerRow: false,
 *                 rows: [[{
 *                             text: "A"
 *                         }, {
 *                             text: "B"
 *                         }, {
 *                             text: "C"
 *                         }], [{
 *                             text: "D"
 *                         }, {
 *                             text: "E"
 *                         }, {
 *                             text: "F"
 *                         }]]
 *             }, {
 *                 type: "columns",
 *                 columns: [{
 *                         blocks: [{
 *                                 type: "paragraph",
 *                                 plaintext: "Marble Column 1 {{email}}"
 *                             }]
 *                     }, {
 *                         blocks: [{
 *                                 type: "image",
 *                                 imageUrl: "https://cdn.britannica.com/89/164789-050-D6B5E2C7/Barack-Obama-2012.jpg",
 *                                 url: "https://www.whitehouse.gov/",
 *                                 title: "Barry O",
 *                                 altText: "A picture of Barry Obama",
 *                                 caption: "One Cool President",
 *                                 captionAlignment: "center",
 *                                 imageAlignment: "right",
 *                                 width: 75
 *                             }]
 *                     }]
 *             }, {
 *                 type: "advertisement",
 *                 opportunityId: "d8dfa6be-24b5-4cad-8350-ae44366dbd4c"
 *             }, {
 *                 type: "image",
 *                 imageUrl: "https://cdn.britannica.com/89/164789-050-D6B5E2C7/Barack-Obama-2012.jpg",
 *                 url: "https://www.whitehouse.gov/",
 *                 title: "Barry O",
 *                 altText: "A picture of Barry Obama",
 *                 caption: "One Cool President",
 *                 captionAlignment: "center",
 *                 imageAlignment: "right",
 *                 width: 75
 *             }, {
 *                 type: "paragraph",
 *                 formattedText: [{
 *                         text: "This is going to be "
 *                     }, {
 *                         text: "a really, really awesome time ",
 *                         styling: ["bold"]
 *                     }, {
 *                         text: "Are you ready for this?",
 *                         styling: ["italic", "bold"]
 *                     }]
 *             }, {
 *                 type: "button",
 *                 href: "/subscribe",
 *                 target: "_blank",
 *                 alignment: "center",
 *                 size: "large",
 *                 text: "Subscribe"
 *             }, {
 *                 type: "button",
 *                 href: "/signup",
 *                 target: "_blank",
 *                 alignment: "right",
 *                 size: "small",
 *                 text: "Sign Up"
 *             }, {
 *                 type: "button",
 *                 href: "/",
 *                 target: "_blank",
 *                 text: "View Posts"
 *             }, {
 *                 type: "heading",
 *                 level: "4",
 *                 textAlignment: "right",
 *                 text: "This is my block!!!",
 *                 anchorHeader: true,
 *                 anchorIncludeInToc: true
 *             }],
 *         postTemplateId: "post_template_00000000-0000-0000-0000-000000000000",
 *         scheduledAt: "2024-12-25T12:00:00Z",
 *         customLinkTrackingEnabled: true,
 *         emailCaptureTypeOverride: "none",
 *         overrideScheduledAt: "2022-10-26T14:01:16Z",
 *         socialShare: "comments_and_likes_only",
 *         thumbnailImageUrl: "https://images.squarespace-cdn.com/content/v1/56e4ca0540261d39b90e4b18/1605047208324-PONGEYKEAKTMM1LANHJ5/1ED706BF-A70B-4F26-B3D5-266B449DDA8A_1_105_c.jpeg",
 *         emailSettings: {
 *             fromAddress: "from_address",
 *             customLiveUrl: "https://beehiiv.com",
 *             displayTitleInEmail: true,
 *             displayBylineInEmail: true,
 *             displaySubtitleInEmail: true,
 *             emailHeaderEngagementButtons: "email_header_engagement_buttons",
 *             emailHeaderSocialShare: "email_header_social_share",
 *             emailPreviewText: "email_preview_text",
 *             emailSubjectLine: "email_subject_line"
 *         },
 *         webSettings: {
 *             displayThumbnailOnWeb: true,
 *             hideFromFeed: true,
 *             slug: "and-this-is-gonna-rock"
 *         },
 *         seoSettings: {
 *             defaultDescription: "default_description",
 *             defaultTitle: "default_title",
 *             ogDescription: "OpenGraph description",
 *             ogTitle: "Opengraph Title",
 *             twitterDescription: "Twitter Stuff",
 *             twitterTitle: "My Twitter Article"
 *         },
 *         contentTags: ["Obama", "Care", "Rocks", "Healthcare"],
 *         recipients: {
 *             web: {
 *                 tierIds: ["premium"]
 *             },
 *             email: {
 *                 tierIds: ["premium", "free"],
 *                 includeSegmentIds: ["seg_6426b403-39f5-42bd-86e9-9533fb0099e7"],
 *                 excludeSegmentIds: ["seg_e34b4085-aef6-449f-a699-7563f915f852"]
 *             }
 *         }
 *     }
 */
export interface PostsCreateRequest {
    /** The content of the post. This is the raw HTML content that will be rendered in the email and web views. */
    bodyContent?: string;
    /** The blocks that make up the post's contents. */
    blocks?: Beehiiv.Block[];
    /** The title of the post. */
    title: string;
    /** The subtitle of the post. */
    subtitle?: string;
    /** The ID of the template to use for the post. If not provided, the default template will be used. */
    postTemplateId?: Beehiiv.PostTemplateId;
    /** The time in which the post will be published. If not provided, the post will be published immediately. */
    scheduledAt?: Date;
    /** If true, custom link tracking will be enabled for this post. If not provided, the default value will be used. */
    customLinkTrackingEnabled?: boolean;
    /** The email capture type to use for this post. If not provided, the default value will be used. */
    emailCaptureTypeOverride?: Beehiiv.PostEmailCaptureTypeOverride;
    /** If you wish to display a date other than the scheduled_at date in the email, you can provide a date here. This will not affect the actual publish date of the post. */
    overrideScheduledAt?: Date;
    /** The social share type to use for this post. If not provided, the default value will be used. */
    socialShare?: Beehiiv.PostSocialShare;
    /** The URL of the thumbnail image to use for the post. If not provided, the default value will be used. */
    thumbnailImageUrl?: string;
    /** The recipients to use for this post. If not provided, the default value will be used. */
    recipients?: Beehiiv.PostRecipients;
    /** The email settings to use for this post. If not provided, the default value will be used. */
    emailSettings?: Beehiiv.PostEmailSettings;
    /** The web settings to use for this post. If not provided, the default value will be used. */
    webSettings?: Beehiiv.PostWebSettings;
    /** The metadata to use for this post. If not provided, the default value will be used. */
    seoSettings?: Beehiiv.PostMetadata;
    /** The content tags to use for this post. If not provided, the default value will be used. */
    contentTags?: string[];
    /** The headers to use for this post. If not provided, the default value will be used. */
    headers?: Record<string, string>;
    /** The custom fields to use for this post. If not provided, the default value will be used. */
    customFields?: Record<string, string>;
}
