/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const AutomationJourneysGetRequestStatus: core.serialization.Schema<
    serializers.AutomationJourneysGetRequestStatus.Raw,
    Beehiiv.AutomationJourneysGetRequestStatus
> = core.serialization.enum_(["in_progress", "completed", "exited_early", "all"]);

export declare namespace AutomationJourneysGetRequestStatus {
    type Raw = "in_progress" | "completed" | "exited_early" | "all";
}
