/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { AutomationJourney } from "../../../types/AutomationJourney";

export const AutomationJourneysIndexResponse: core.serialization.ObjectSchema<
    serializers.AutomationJourneysIndexResponse.Raw,
    Beehiiv.AutomationJourneysIndexResponse
> = core.serialization.object({
    data: core.serialization.list(AutomationJourney),
    limit: core.serialization.number(),
    page: core.serialization.number(),
    totalResults: core.serialization.property("total_results", core.serialization.number()),
    totalPages: core.serialization.property("total_pages", core.serialization.number()),
});

export declare namespace AutomationJourneysIndexResponse {
    interface Raw {
        data: AutomationJourney.Raw[];
        limit: number;
        page: number;
        total_results: number;
        total_pages: number;
    }
}
