/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { AutomationJourney } from "../../../types/AutomationJourney";

export const AutomationJourneysResponse: core.serialization.ObjectSchema<
    serializers.AutomationJourneysResponse.Raw,
    Beehiiv.AutomationJourneysResponse
> = core.serialization.object({
    data: AutomationJourney,
});

export declare namespace AutomationJourneysResponse {
    interface Raw {
        data: AutomationJourney.Raw;
    }
}
