/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class BeehiivTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, BeehiivTimeoutError.prototype);
    }
}
