/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of update (status or bulk)
 */
export type BulkSubscriptionUpdatesListResponseDataItemType = "status" | "bulk";

export const BulkSubscriptionUpdatesListResponseDataItemType = {
    Status: "status",
    Bulk: "bulk",
} as const;
