/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the update
 */
export type BulkSubscriptionUpdatesGetResponseDataStatus = "pending" | "processing" | "complete" | "failed";

export const BulkSubscriptionUpdatesGetResponseDataStatus = {
    Pending: "pending",
    Processing: "processing",
    Complete: "complete",
    Failed: "failed",
} as const;
