/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of update (status or bulk)
 */
export type BulkSubscriptionUpdatesGetResponseDataType = "bulk" | "status";

export const BulkSubscriptionUpdatesGetResponseDataType = {
    Bulk: "bulk",
    Status: "status",
} as const;
