/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The Tier of the Subscription (not required)
 */
export type SubscriptionsPutRequestSubscriptionsItemTier = "free" | "premium";

export const SubscriptionsPutRequestSubscriptionsItemTier = {
    Free: "free",
    Premium: "premium",
} as const;
