/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../index";

export interface SubscriptionsPatchRequestSubscriptionsItemCustomFieldsItem {
    /** The display value of the custom field */
    name?: string;
    /** The value of the custom field */
    value?: Beehiiv.CustomFieldDataType;
    /** A boolean value to specify whether to delete this custom field entry from the subscription */
    delete?: boolean;
}
