/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         subscriptionIds: ["sub_1234-5678-9012-3456-7890", "sub_9876-5432-1098-7654-3210"],
 *         newStatus: "active"
 *     }
 */
export interface BulkSubscriptionsStatusPatchRequest {
    /** An array of subscription IDs to be updated */
    subscriptionIds: string[];
    /** The new status to set for the subscriptions */
    newStatus: string;
}
