/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const EmailBlastsListRequestOrderBy: core.serialization.Schema<
    serializers.EmailBlastsListRequestOrderBy.Raw,
    Beehiiv.EmailBlastsListRequestOrderBy
> = core.serialization.enum_(["created", "last_sent"]);

export declare namespace EmailBlastsListRequestOrderBy {
    type Raw = "created" | "last_sent";
}
