/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const EmailBlastsListRequestStatus: core.serialization.Schema<
    serializers.EmailBlastsListRequestStatus.Raw,
    Beehiiv.EmailBlastsListRequestStatus
> = core.serialization.enum_(["active", "inactive"]);

export declare namespace EmailBlastsListRequestStatus {
    type Raw = "active" | "inactive";
}
