/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const EmailBlastsListRequestExpandItem: core.serialization.Schema<
    serializers.EmailBlastsListRequestExpandItem.Raw,
    Beehiiv.EmailBlastsListRequestExpandItem
> = core.serialization.enum_(["stats"]);

export declare namespace EmailBlastsListRequestExpandItem {
    type Raw = "stats";
}
