/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { EmailBlast } from "../../../types/EmailBlast";

export const EmailBlastsGetResponse: core.serialization.ObjectSchema<
    serializers.EmailBlastsGetResponse.Raw,
    Beehiiv.EmailBlastsGetResponse
> = core.serialization.object({
    data: EmailBlast,
});

export declare namespace EmailBlastsGetResponse {
    interface Raw {
        data: EmailBlast.Raw;
    }
}
