/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { EmailBlast } from "../../../types/EmailBlast";

export const EmailBlastsListResponse: core.serialization.ObjectSchema<
    serializers.EmailBlastsListResponse.Raw,
    Beehiiv.EmailBlastsListResponse
> = core.serialization.object({
    data: core.serialization.list(EmailBlast),
    limit: core.serialization.number(),
    page: core.serialization.number(),
    totalResults: core.serialization.property("total_results", core.serialization.number()),
    totalPages: core.serialization.property("total_pages", core.serialization.number()),
});

export declare namespace EmailBlastsListResponse {
    interface Raw {
        data: EmailBlast.Raw[];
        limit: number;
        page: number;
        total_results: number;
        total_pages: number;
    }
}
