/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { Subscription } from "../../../types/Subscription";

export const SubscriptionTagsCreateResponse: core.serialization.ObjectSchema<
    serializers.SubscriptionTagsCreateResponse.Raw,
    Beehiiv.SubscriptionTagsCreateResponse
> = core.serialization.object({
    data: Subscription.optional(),
});

export declare namespace SubscriptionTagsCreateResponse {
    interface Raw {
        data?: Subscription.Raw | null;
    }
}
