/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         display: "New Display"
 *     }
 */
export interface CustomFieldsPatchRequest {
    display?: string;
}
