/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const AutomationId: core.serialization.Schema<serializers.AutomationId.Raw, Beehiiv.AutomationId> =
    core.serialization.string();

export declare namespace AutomationId {
    type Raw = string;
}
