/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const AutomationJourneyId: core.serialization.Schema<
    serializers.AutomationJourneyId.Raw,
    Beehiiv.AutomationJourneyId
> = core.serialization.string();

export declare namespace AutomationJourneyId {
    type Raw = string;
}
