/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const MilestoneId: core.serialization.Schema<serializers.MilestoneId.Raw, Beehiiv.MilestoneId> =
    core.serialization.string();

export declare namespace MilestoneId {
    type Raw = string;
}
