/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const PostTemplateId: core.serialization.Schema<serializers.PostTemplateId.Raw, Beehiiv.PostTemplateId> =
    core.serialization.string();

export declare namespace PostTemplateId {
    type Raw = string;
}
