/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const PriceId: core.serialization.Schema<serializers.PriceId.Raw, Beehiiv.PriceId> = core.serialization.string();

export declare namespace PriceId {
    type Raw = string;
}
