/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const RewardId: core.serialization.Schema<serializers.RewardId.Raw, Beehiiv.RewardId> =
    core.serialization.string();

export declare namespace RewardId {
    type Raw = string;
}
