/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const SegmentId: core.serialization.Schema<serializers.SegmentId.Raw, Beehiiv.SegmentId> =
    core.serialization.string();

export declare namespace SegmentId {
    type Raw = string;
}
