/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const TierId: core.serialization.Schema<serializers.TierId.Raw, Beehiiv.TierId> = core.serialization.string();

export declare namespace TierId {
    type Raw = string;
}
