/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Beehiiv from "../../../../../api/index";
import * as core from "../../../../../core";
import { SubscriptionsPatchRequestSubscriptionsItem } from "../../types/SubscriptionsPatchRequestSubscriptionsItem";

export const BulkSubscriptionsPutRequest: core.serialization.Schema<
    serializers.BulkSubscriptionsPutRequest.Raw,
    Beehiiv.BulkSubscriptionsPutRequest
> = core.serialization.object({
    subscriptions: core.serialization.list(SubscriptionsPatchRequestSubscriptionsItem).optional(),
});

export declare namespace BulkSubscriptionsPutRequest {
    interface Raw {
        subscriptions?: SubscriptionsPatchRequestSubscriptionsItem.Raw[] | null;
    }
}
