/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Beehiiv from "../../../../../api/index";
import * as core from "../../../../../core";

export const BulkSubscriptionsStatusPatchRequest: core.serialization.Schema<
    serializers.BulkSubscriptionsStatusPatchRequest.Raw,
    Beehiiv.BulkSubscriptionsStatusPatchRequest
> = core.serialization.object({
    subscriptionIds: core.serialization.property(
        "subscription_ids",
        core.serialization.list(core.serialization.string())
    ),
    newStatus: core.serialization.property("new_status", core.serialization.string()),
});

export declare namespace BulkSubscriptionsStatusPatchRequest {
    interface Raw {
        subscription_ids: string[];
        new_status: string;
    }
}
