/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Beehiiv from "../../../../../api/index";
import * as core from "../../../../../core";
import { SubscriptionsPatchRequestSubscriptionsItem } from "../../types/SubscriptionsPatchRequestSubscriptionsItem";

export const BulkSubscriptionsPatchRequest: core.serialization.Schema<
    serializers.BulkSubscriptionsPatchRequest.Raw,
    Beehiiv.BulkSubscriptionsPatchRequest
> = core.serialization.object({
    subscriptions: core.serialization.list(SubscriptionsPatchRequestSubscriptionsItem).optional(),
});

export declare namespace BulkSubscriptionsPatchRequest {
    interface Raw {
        subscriptions?: SubscriptionsPatchRequestSubscriptionsItem.Raw[] | null;
    }
}
