/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../../index";

/**
 * @example
 *     {}
 */
export interface EmailBlastsGetRequest {
    /**
     * Optional list of expandable objects.
     */
    expand?: Beehiiv.EmailBlastsGetRequestExpandItem | Beehiiv.EmailBlastsGetRequestExpandItem[];
}
