/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EmailBlastsListRequestExpandItem =
    /**
     * Returns statistics about the email blast(s). */
    "stats";

export const EmailBlastsListRequestExpandItem = {
    Stats: "stats",
} as const;
