/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EmailBlastsListRequestStatus = "active" | "inactive";

export const EmailBlastsListRequestStatus = {
    Active: "active",
    Inactive: "inactive",
} as const;
