/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EmailBlastsListRequestOrderBy = "created" | "last_sent";

export const EmailBlastsListRequestOrderBy = {
    Created: "created",
    LastSent: "last_sent",
} as const;
