/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EmailBlastsGetRequestExpandItem =
    /**
     * Returns statistics about the email blast. */
    "stats";

export const EmailBlastsGetRequestExpandItem = {
    Stats: "stats",
} as const;
