/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Beehiiv from "../../../../index";

/**
 * @example
 *     {
 *         email: "test@example.com",
 *         doubleOptOverride: "on"
 *     }
 */
export interface AutomationJourneysCreateRequest {
    /** The email address associated with the subscription. */
    email?: string;
    subscriptionId?: Beehiiv.SubscriptionId;
    /** Override publication double-opt settings for this subscription. */
    doubleOptOverride?: Beehiiv.DoubleOptOverride;
}
