/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { Tier } from "./Tier";

export const IndexTiersResponse: core.serialization.ObjectSchema<
    serializers.IndexTiersResponse.Raw,
    Beehiiv.IndexTiersResponse
> = core.serialization.object({
    data: core.serialization.list(Tier),
    limit: core.serialization.number(),
    page: core.serialization.number(),
    totalResults: core.serialization.property("total_results", core.serialization.number()),
    totalPages: core.serialization.property("total_pages", core.serialization.number()),
});

export declare namespace IndexTiersResponse {
    interface Raw {
        data: Tier.Raw[];
        limit: number;
        page: number;
        total_results: number;
        total_pages: number;
    }
}
