/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { Tier } from "./Tier";

export const TierResponse: core.serialization.ObjectSchema<serializers.TierResponse.Raw, Beehiiv.TierResponse> =
    core.serialization.object({
        data: Tier.optional(),
    });

export declare namespace TierResponse {
    interface Raw {
        data?: Tier.Raw | null;
    }
}
