/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { PriceId } from "../../ids/types/PriceId";
import { TierPriceCurrency } from "./TierPriceCurrency";
import { TierPriceInterval } from "./TierPriceInterval";

export const TierPrice: core.serialization.ObjectSchema<serializers.TierPrice.Raw, Beehiiv.TierPrice> =
    core.serialization.object({
        id: PriceId.optional(),
        currency: TierPriceCurrency.optional(),
        amountCents: core.serialization.property("amount_cents", core.serialization.number().optional()),
        enabled: core.serialization.boolean().optional(),
        interval: TierPriceInterval.optional(),
        denominator: core.serialization.string().optional(),
        cta: core.serialization.string().optional(),
        features: core.serialization.list(core.serialization.string()).optional(),
    });

export declare namespace TierPrice {
    interface Raw {
        id?: PriceId.Raw | null;
        currency?: TierPriceCurrency.Raw | null;
        amount_cents?: number | null;
        enabled?: boolean | null;
        interval?: TierPriceInterval.Raw | null;
        denominator?: string | null;
        cta?: string | null;
        features?: string[] | null;
    }
}
