/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const TierStatus: core.serialization.Schema<serializers.TierStatus.Raw, Beehiiv.TierStatus> =
    core.serialization.enum_(["active", "archived"]);

export declare namespace TierStatus {
    type Raw = "active" | "archived";
}
