/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";

export const TierPriceCurrency: core.serialization.Schema<
    serializers.TierPriceCurrency.Raw,
    Beehiiv.TierPriceCurrency
> = core.serialization.enum_(["usd", "aud", "cad", "eur", "inr", "brl"]);

export declare namespace TierPriceCurrency {
    type Raw = "usd" | "aud" | "cad" | "eur" | "inr" | "brl";
}
