/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Beehiiv from "../../../../api/index";
import * as core from "../../../../core";
import { PriceId } from "../../ids/types/PriceId";
import { TierPriceCurrency } from "./TierPriceCurrency";
import { TierPriceInterval } from "./TierPriceInterval";

export const UpdateTierPriceRequest: core.serialization.ObjectSchema<
    serializers.UpdateTierPriceRequest.Raw,
    Beehiiv.UpdateTierPriceRequest
> = core.serialization.object({
    id: PriceId,
    currency: TierPriceCurrency,
    amountCents: core.serialization.property("amount_cents", core.serialization.number()),
    interval: TierPriceInterval,
    intervalDisplay: core.serialization.property("interval_display", core.serialization.string().optional()),
    cta: core.serialization.string().optional(),
    features: core.serialization.list(core.serialization.string()).optional(),
    delete: core.serialization.boolean().optional(),
});

export declare namespace UpdateTierPriceRequest {
    interface Raw {
        id: PriceId.Raw;
        currency: TierPriceCurrency.Raw;
        amount_cents: number;
        interval: TierPriceInterval.Raw;
        interval_display?: string | null;
        cta?: string | null;
        features?: string[] | null;
        delete?: boolean | null;
    }
}
