/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SegmentsExpandItems =
    /**
     * Requests the most recently calculated statistics for a segment. */
    "stats";

export const SegmentsExpandItems = {
    Stats: "stats",
} as const;
