/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface SubscriptionTagsCreateRequest {
    /** Tags that can be used to group subscribers */
    tags?: string[];
}
